services:
  postgresql:
    restart: unless-stopped
    image: postgres:latest
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: guest

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.13.0-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources
      
  temporal:
    container_name: temporal
    restart: unless-stopped
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PWD=${DB_PASS}
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/dev-sql.yaml
    image: temporalio/auto-setup:1.24.2
    ports:
      - 7233:7233
    volumes:
      - ./docker/temporal:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      - DB=postgres12
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PWD=${DB_PASS}
      - POSTGRES_SEEDS=postgresql
      - VISIBILITY_DBNAME=temporal
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.24.2-tctl-1.18.1-cli-0.13.0
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.26.2
    ports:
      - 8080:8080
      
volumes:
  prom_data: