// Code generated by ent, DO NOT EDIT.

package card

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUpdateTime, v))
}

// PlayerID applies equality check predicate on the "player_id" field. It's identical to PlayerIDEQ.
func PlayerID(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldPlayerID, v))
}

// CardType applies equality check predicate on the "card_type" field. It's identical to CardTypeEQ.
func CardType(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCardType, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldPosition, v))
}

// Available applies equality check predicate on the "available" field. It's identical to AvailableEQ.
func Available(v bool) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldAvailable, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldLevel, v))
}

// ExperiencePoints applies equality check predicate on the "experience_points" field. It's identical to ExperiencePointsEQ.
func ExperiencePoints(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldExperiencePoints, v))
}

// ExperiencePointsThreshold applies equality check predicate on the "experience_points_threshold" field. It's identical to ExperiencePointsThresholdEQ.
func ExperiencePointsThreshold(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldExperiencePointsThreshold, v))
}

// Rarity applies equality check predicate on the "rarity" field. It's identical to RarityEQ.
func Rarity(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldRarity, v))
}

// Buffs applies equality check predicate on the "buffs" field. It's identical to BuffsEQ.
func Buffs(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldBuffs, v))
}

// IndividualValue applies equality check predicate on the "individual_value" field. It's identical to IndividualValueEQ.
func IndividualValue(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldIndividualValue, v))
}

// OwnedAt applies equality check predicate on the "owned_at" field. It's identical to OwnedAtEQ.
func OwnedAt(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOwnedAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldUpdateTime, v))
}

// PlayerIDEQ applies the EQ predicate on the "player_id" field.
func PlayerIDEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldPlayerID, v))
}

// PlayerIDNEQ applies the NEQ predicate on the "player_id" field.
func PlayerIDNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldPlayerID, v))
}

// PlayerIDIn applies the In predicate on the "player_id" field.
func PlayerIDIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldPlayerID, vs...))
}

// PlayerIDNotIn applies the NotIn predicate on the "player_id" field.
func PlayerIDNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldPlayerID, vs...))
}

// PlayerIDGT applies the GT predicate on the "player_id" field.
func PlayerIDGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldPlayerID, v))
}

// PlayerIDGTE applies the GTE predicate on the "player_id" field.
func PlayerIDGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldPlayerID, v))
}

// PlayerIDLT applies the LT predicate on the "player_id" field.
func PlayerIDLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldPlayerID, v))
}

// PlayerIDLTE applies the LTE predicate on the "player_id" field.
func PlayerIDLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldPlayerID, v))
}

// PlayerIDContains applies the Contains predicate on the "player_id" field.
func PlayerIDContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldPlayerID, v))
}

// PlayerIDHasPrefix applies the HasPrefix predicate on the "player_id" field.
func PlayerIDHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldPlayerID, v))
}

// PlayerIDHasSuffix applies the HasSuffix predicate on the "player_id" field.
func PlayerIDHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldPlayerID, v))
}

// PlayerIDEqualFold applies the EqualFold predicate on the "player_id" field.
func PlayerIDEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldPlayerID, v))
}

// PlayerIDContainsFold applies the ContainsFold predicate on the "player_id" field.
func PlayerIDContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldPlayerID, v))
}

// CardTypeEQ applies the EQ predicate on the "card_type" field.
func CardTypeEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldCardType, v))
}

// CardTypeNEQ applies the NEQ predicate on the "card_type" field.
func CardTypeNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldCardType, v))
}

// CardTypeIn applies the In predicate on the "card_type" field.
func CardTypeIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldCardType, vs...))
}

// CardTypeNotIn applies the NotIn predicate on the "card_type" field.
func CardTypeNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldCardType, vs...))
}

// CardTypeGT applies the GT predicate on the "card_type" field.
func CardTypeGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldCardType, v))
}

// CardTypeGTE applies the GTE predicate on the "card_type" field.
func CardTypeGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldCardType, v))
}

// CardTypeLT applies the LT predicate on the "card_type" field.
func CardTypeLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldCardType, v))
}

// CardTypeLTE applies the LTE predicate on the "card_type" field.
func CardTypeLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldCardType, v))
}

// CardTypeContains applies the Contains predicate on the "card_type" field.
func CardTypeContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldCardType, v))
}

// CardTypeHasPrefix applies the HasPrefix predicate on the "card_type" field.
func CardTypeHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldCardType, v))
}

// CardTypeHasSuffix applies the HasSuffix predicate on the "card_type" field.
func CardTypeHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldCardType, v))
}

// CardTypeEqualFold applies the EqualFold predicate on the "card_type" field.
func CardTypeEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldCardType, v))
}

// CardTypeContainsFold applies the ContainsFold predicate on the "card_type" field.
func CardTypeContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldCardType, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v float64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v float64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldPosition, v))
}

// AvailableEQ applies the EQ predicate on the "available" field.
func AvailableEQ(v bool) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldAvailable, v))
}

// AvailableNEQ applies the NEQ predicate on the "available" field.
func AvailableNEQ(v bool) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldAvailable, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldLevel, v))
}

// ExperiencePointsEQ applies the EQ predicate on the "experience_points" field.
func ExperiencePointsEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldExperiencePoints, v))
}

// ExperiencePointsNEQ applies the NEQ predicate on the "experience_points" field.
func ExperiencePointsNEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldExperiencePoints, v))
}

// ExperiencePointsIn applies the In predicate on the "experience_points" field.
func ExperiencePointsIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldExperiencePoints, vs...))
}

// ExperiencePointsNotIn applies the NotIn predicate on the "experience_points" field.
func ExperiencePointsNotIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldExperiencePoints, vs...))
}

// ExperiencePointsGT applies the GT predicate on the "experience_points" field.
func ExperiencePointsGT(v int64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldExperiencePoints, v))
}

// ExperiencePointsGTE applies the GTE predicate on the "experience_points" field.
func ExperiencePointsGTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldExperiencePoints, v))
}

// ExperiencePointsLT applies the LT predicate on the "experience_points" field.
func ExperiencePointsLT(v int64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldExperiencePoints, v))
}

// ExperiencePointsLTE applies the LTE predicate on the "experience_points" field.
func ExperiencePointsLTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldExperiencePoints, v))
}

// ExperiencePointsThresholdEQ applies the EQ predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldExperiencePointsThreshold, v))
}

// ExperiencePointsThresholdNEQ applies the NEQ predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdNEQ(v int64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldExperiencePointsThreshold, v))
}

// ExperiencePointsThresholdIn applies the In predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldExperiencePointsThreshold, vs...))
}

// ExperiencePointsThresholdNotIn applies the NotIn predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdNotIn(vs ...int64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldExperiencePointsThreshold, vs...))
}

// ExperiencePointsThresholdGT applies the GT predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdGT(v int64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldExperiencePointsThreshold, v))
}

// ExperiencePointsThresholdGTE applies the GTE predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdGTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldExperiencePointsThreshold, v))
}

// ExperiencePointsThresholdLT applies the LT predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdLT(v int64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldExperiencePointsThreshold, v))
}

// ExperiencePointsThresholdLTE applies the LTE predicate on the "experience_points_threshold" field.
func ExperiencePointsThresholdLTE(v int64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldExperiencePointsThreshold, v))
}

// RarityEQ applies the EQ predicate on the "rarity" field.
func RarityEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldRarity, v))
}

// RarityNEQ applies the NEQ predicate on the "rarity" field.
func RarityNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldRarity, v))
}

// RarityIn applies the In predicate on the "rarity" field.
func RarityIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldRarity, vs...))
}

// RarityNotIn applies the NotIn predicate on the "rarity" field.
func RarityNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldRarity, vs...))
}

// RarityGT applies the GT predicate on the "rarity" field.
func RarityGT(v int) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldRarity, v))
}

// RarityGTE applies the GTE predicate on the "rarity" field.
func RarityGTE(v int) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldRarity, v))
}

// RarityLT applies the LT predicate on the "rarity" field.
func RarityLT(v int) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldRarity, v))
}

// RarityLTE applies the LTE predicate on the "rarity" field.
func RarityLTE(v int) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldRarity, v))
}

// BuffsEQ applies the EQ predicate on the "buffs" field.
func BuffsEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldBuffs, v))
}

// BuffsNEQ applies the NEQ predicate on the "buffs" field.
func BuffsNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldBuffs, v))
}

// BuffsIn applies the In predicate on the "buffs" field.
func BuffsIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldBuffs, vs...))
}

// BuffsNotIn applies the NotIn predicate on the "buffs" field.
func BuffsNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldBuffs, vs...))
}

// BuffsGT applies the GT predicate on the "buffs" field.
func BuffsGT(v int) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldBuffs, v))
}

// BuffsGTE applies the GTE predicate on the "buffs" field.
func BuffsGTE(v int) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldBuffs, v))
}

// BuffsLT applies the LT predicate on the "buffs" field.
func BuffsLT(v int) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldBuffs, v))
}

// BuffsLTE applies the LTE predicate on the "buffs" field.
func BuffsLTE(v int) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldBuffs, v))
}

// IndividualValueEQ applies the EQ predicate on the "individual_value" field.
func IndividualValueEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldIndividualValue, v))
}

// IndividualValueNEQ applies the NEQ predicate on the "individual_value" field.
func IndividualValueNEQ(v float64) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldIndividualValue, v))
}

// IndividualValueIn applies the In predicate on the "individual_value" field.
func IndividualValueIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldIndividualValue, vs...))
}

// IndividualValueNotIn applies the NotIn predicate on the "individual_value" field.
func IndividualValueNotIn(vs ...float64) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldIndividualValue, vs...))
}

// IndividualValueGT applies the GT predicate on the "individual_value" field.
func IndividualValueGT(v float64) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldIndividualValue, v))
}

// IndividualValueGTE applies the GTE predicate on the "individual_value" field.
func IndividualValueGTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldIndividualValue, v))
}

// IndividualValueLT applies the LT predicate on the "individual_value" field.
func IndividualValueLT(v float64) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldIndividualValue, v))
}

// IndividualValueLTE applies the LTE predicate on the "individual_value" field.
func IndividualValueLTE(v float64) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldIndividualValue, v))
}

// OwnedAtEQ applies the EQ predicate on the "owned_at" field.
func OwnedAtEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOwnedAt, v))
}

// OwnedAtNEQ applies the NEQ predicate on the "owned_at" field.
func OwnedAtNEQ(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldOwnedAt, v))
}

// OwnedAtIn applies the In predicate on the "owned_at" field.
func OwnedAtIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldOwnedAt, vs...))
}

// OwnedAtNotIn applies the NotIn predicate on the "owned_at" field.
func OwnedAtNotIn(vs ...time.Time) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldOwnedAt, vs...))
}

// OwnedAtGT applies the GT predicate on the "owned_at" field.
func OwnedAtGT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldOwnedAt, v))
}

// OwnedAtGTE applies the GTE predicate on the "owned_at" field.
func OwnedAtGTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldOwnedAt, v))
}

// OwnedAtLT applies the LT predicate on the "owned_at" field.
func OwnedAtLT(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldOwnedAt, v))
}

// OwnedAtLTE applies the LTE predicate on the "owned_at" field.
func OwnedAtLTE(v time.Time) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldOwnedAt, v))
}

// HasOwnedBy applies the HasEdge predicate on the "owned_by" edge.
func HasOwnedBy() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnedByTable, OwnedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnedByWith applies the HasEdge predicate on the "owned_by" edge with a given conditions (other predicates).
func HasOwnedByWith(preds ...predicate.Player) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newOwnedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInFavoritesOf applies the HasEdge predicate on the "in_favorites_of" edge.
func HasInFavoritesOf() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, InFavoritesOfTable, InFavoritesOfPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInFavoritesOfWith applies the HasEdge predicate on the "in_favorites_of" edge with a given conditions (other predicates).
func HasInFavoritesOfWith(preds ...predicate.Player) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newInFavoritesOfStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInDeckOf applies the HasEdge predicate on the "in_deck_of" edge.
func HasInDeckOf() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, InDeckOfTable, InDeckOfPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInDeckOfWith applies the HasEdge predicate on the "in_deck_of" edge with a given conditions (other predicates).
func HasInDeckOfWith(preds ...predicate.Player) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newInDeckOfStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasType applies the HasEdge predicate on the "type" edge.
func HasType() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TypeTable, TypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTypeWith applies the HasEdge predicate on the "type" edge with a given conditions (other predicates).
func HasTypeWith(preds ...predicate.CardType) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStats applies the HasEdge predicate on the "stats" edge.
func HasStats() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, StatsTable, StatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatsWith applies the HasEdge predicate on the "stats" edge with a given conditions (other predicates).
func HasStatsWith(preds ...predicate.CardStats) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newStatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlayerFavoriteCards applies the HasEdge predicate on the "player_favorite_cards" edge.
func HasPlayerFavoriteCards() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PlayerFavoriteCardsTable, PlayerFavoriteCardsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerFavoriteCardsWith applies the HasEdge predicate on the "player_favorite_cards" edge with a given conditions (other predicates).
func HasPlayerFavoriteCardsWith(preds ...predicate.PlayerFavoriteCards) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newPlayerFavoriteCardsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlayerDecks applies the HasEdge predicate on the "player_decks" edge.
func HasPlayerDecks() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PlayerDecksTable, PlayerDecksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerDecksWith applies the HasEdge predicate on the "player_decks" edge with a given conditions (other predicates).
func HasPlayerDecksWith(preds ...predicate.PlayerDeck) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newPlayerDecksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Card) predicate.Card {
	return predicate.Card(sql.NotPredicates(p))
}
