-- migrate:up
ALTER TABLE players
ADD COLUMN liens BIGINT NOT NULL DEFAULT 500,
ADD COLUMN level INT NOT NULL DEFAULT 0,
ADD COLUMN xp BIGINT NOT NULL DEFAULT 0,
ADD COLUMN next_level_xp BIGINT NOT NULL DEFAULT 20,
ADD COLUMN backpack_level INT NOT NULL DEFAULT 1;

-- migrate:down
ALTER TABLE players
DROP COLUMN liens,
DROP COLUMN level,
DROP COLUMN xp,
DROP COLUMN next_level_xp,
DROP COLUMN backpack_level;
