// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/auction"
	"github.com/yyewolf/rwbyadv3/ent/auctionbid"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
)

// AuctionBidQuery is the builder for querying AuctionBid entities.
type AuctionBidQuery struct {
	config
	ctx         *QueryContext
	order       []auctionbid.OrderOption
	inters      []Interceptor
	predicates  []predicate.AuctionBid
	withAuction *AuctionQuery
	withPlayer  *PlayerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuctionBidQuery builder.
func (abq *AuctionBidQuery) Where(ps ...predicate.AuctionBid) *AuctionBidQuery {
	abq.predicates = append(abq.predicates, ps...)
	return abq
}

// Limit the number of records to be returned by this query.
func (abq *AuctionBidQuery) Limit(limit int) *AuctionBidQuery {
	abq.ctx.Limit = &limit
	return abq
}

// Offset to start from.
func (abq *AuctionBidQuery) Offset(offset int) *AuctionBidQuery {
	abq.ctx.Offset = &offset
	return abq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (abq *AuctionBidQuery) Unique(unique bool) *AuctionBidQuery {
	abq.ctx.Unique = &unique
	return abq
}

// Order specifies how the records should be ordered.
func (abq *AuctionBidQuery) Order(o ...auctionbid.OrderOption) *AuctionBidQuery {
	abq.order = append(abq.order, o...)
	return abq
}

// QueryAuction chains the current query on the "auction" edge.
func (abq *AuctionBidQuery) QueryAuction() *AuctionQuery {
	query := (&AuctionClient{config: abq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := abq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := abq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(auctionbid.Table, auctionbid.FieldID, selector),
			sqlgraph.To(auction.Table, auction.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, auctionbid.AuctionTable, auctionbid.AuctionColumn),
		)
		fromU = sqlgraph.SetNeighbors(abq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlayer chains the current query on the "player" edge.
func (abq *AuctionBidQuery) QueryPlayer() *PlayerQuery {
	query := (&PlayerClient{config: abq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := abq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := abq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(auctionbid.Table, auctionbid.FieldID, selector),
			sqlgraph.To(player.Table, player.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, auctionbid.PlayerTable, auctionbid.PlayerColumn),
		)
		fromU = sqlgraph.SetNeighbors(abq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AuctionBid entity from the query.
// Returns a *NotFoundError when no AuctionBid was found.
func (abq *AuctionBidQuery) First(ctx context.Context) (*AuctionBid, error) {
	nodes, err := abq.Limit(1).All(setContextOp(ctx, abq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{auctionbid.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (abq *AuctionBidQuery) FirstX(ctx context.Context) *AuctionBid {
	node, err := abq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuctionBid ID from the query.
// Returns a *NotFoundError when no AuctionBid ID was found.
func (abq *AuctionBidQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = abq.Limit(1).IDs(setContextOp(ctx, abq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{auctionbid.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (abq *AuctionBidQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := abq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuctionBid entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuctionBid entity is found.
// Returns a *NotFoundError when no AuctionBid entities are found.
func (abq *AuctionBidQuery) Only(ctx context.Context) (*AuctionBid, error) {
	nodes, err := abq.Limit(2).All(setContextOp(ctx, abq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{auctionbid.Label}
	default:
		return nil, &NotSingularError{auctionbid.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (abq *AuctionBidQuery) OnlyX(ctx context.Context) *AuctionBid {
	node, err := abq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuctionBid ID in the query.
// Returns a *NotSingularError when more than one AuctionBid ID is found.
// Returns a *NotFoundError when no entities are found.
func (abq *AuctionBidQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = abq.Limit(2).IDs(setContextOp(ctx, abq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{auctionbid.Label}
	default:
		err = &NotSingularError{auctionbid.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (abq *AuctionBidQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := abq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuctionBids.
func (abq *AuctionBidQuery) All(ctx context.Context) ([]*AuctionBid, error) {
	ctx = setContextOp(ctx, abq.ctx, ent.OpQueryAll)
	if err := abq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuctionBid, *AuctionBidQuery]()
	return withInterceptors[[]*AuctionBid](ctx, abq, qr, abq.inters)
}

// AllX is like All, but panics if an error occurs.
func (abq *AuctionBidQuery) AllX(ctx context.Context) []*AuctionBid {
	nodes, err := abq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuctionBid IDs.
func (abq *AuctionBidQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if abq.ctx.Unique == nil && abq.path != nil {
		abq.Unique(true)
	}
	ctx = setContextOp(ctx, abq.ctx, ent.OpQueryIDs)
	if err = abq.Select(auctionbid.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (abq *AuctionBidQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := abq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (abq *AuctionBidQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, abq.ctx, ent.OpQueryCount)
	if err := abq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, abq, querierCount[*AuctionBidQuery](), abq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (abq *AuctionBidQuery) CountX(ctx context.Context) int {
	count, err := abq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (abq *AuctionBidQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, abq.ctx, ent.OpQueryExist)
	switch _, err := abq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (abq *AuctionBidQuery) ExistX(ctx context.Context) bool {
	exist, err := abq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuctionBidQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (abq *AuctionBidQuery) Clone() *AuctionBidQuery {
	if abq == nil {
		return nil
	}
	return &AuctionBidQuery{
		config:      abq.config,
		ctx:         abq.ctx.Clone(),
		order:       append([]auctionbid.OrderOption{}, abq.order...),
		inters:      append([]Interceptor{}, abq.inters...),
		predicates:  append([]predicate.AuctionBid{}, abq.predicates...),
		withAuction: abq.withAuction.Clone(),
		withPlayer:  abq.withPlayer.Clone(),
		// clone intermediate query.
		sql:  abq.sql.Clone(),
		path: abq.path,
	}
}

// WithAuction tells the query-builder to eager-load the nodes that are connected to
// the "auction" edge. The optional arguments are used to configure the query builder of the edge.
func (abq *AuctionBidQuery) WithAuction(opts ...func(*AuctionQuery)) *AuctionBidQuery {
	query := (&AuctionClient{config: abq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	abq.withAuction = query
	return abq
}

// WithPlayer tells the query-builder to eager-load the nodes that are connected to
// the "player" edge. The optional arguments are used to configure the query builder of the edge.
func (abq *AuctionBidQuery) WithPlayer(opts ...func(*PlayerQuery)) *AuctionBidQuery {
	query := (&PlayerClient{config: abq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	abq.withPlayer = query
	return abq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuctionBid.Query().
//		GroupBy(auctionbid.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (abq *AuctionBidQuery) GroupBy(field string, fields ...string) *AuctionBidGroupBy {
	abq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AuctionBidGroupBy{build: abq}
	grbuild.flds = &abq.ctx.Fields
	grbuild.label = auctionbid.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.AuctionBid.Query().
//		Select(auctionbid.FieldCreateTime).
//		Scan(ctx, &v)
func (abq *AuctionBidQuery) Select(fields ...string) *AuctionBidSelect {
	abq.ctx.Fields = append(abq.ctx.Fields, fields...)
	sbuild := &AuctionBidSelect{AuctionBidQuery: abq}
	sbuild.label = auctionbid.Label
	sbuild.flds, sbuild.scan = &abq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuctionBidSelect configured with the given aggregations.
func (abq *AuctionBidQuery) Aggregate(fns ...AggregateFunc) *AuctionBidSelect {
	return abq.Select().Aggregate(fns...)
}

func (abq *AuctionBidQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range abq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, abq); err != nil {
				return err
			}
		}
	}
	for _, f := range abq.ctx.Fields {
		if !auctionbid.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if abq.path != nil {
		prev, err := abq.path(ctx)
		if err != nil {
			return err
		}
		abq.sql = prev
	}
	return nil
}

func (abq *AuctionBidQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuctionBid, error) {
	var (
		nodes       = []*AuctionBid{}
		_spec       = abq.querySpec()
		loadedTypes = [2]bool{
			abq.withAuction != nil,
			abq.withPlayer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuctionBid).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuctionBid{config: abq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, abq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := abq.withAuction; query != nil {
		if err := abq.loadAuction(ctx, query, nodes, nil,
			func(n *AuctionBid, e *Auction) { n.Edges.Auction = e }); err != nil {
			return nil, err
		}
	}
	if query := abq.withPlayer; query != nil {
		if err := abq.loadPlayer(ctx, query, nodes, nil,
			func(n *AuctionBid, e *Player) { n.Edges.Player = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (abq *AuctionBidQuery) loadAuction(ctx context.Context, query *AuctionQuery, nodes []*AuctionBid, init func(*AuctionBid), assign func(*AuctionBid, *Auction)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AuctionBid)
	for i := range nodes {
		fk := nodes[i].AuctionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(auction.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "auction_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (abq *AuctionBidQuery) loadPlayer(ctx context.Context, query *PlayerQuery, nodes []*AuctionBid, init func(*AuctionBid), assign func(*AuctionBid, *Player)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*AuctionBid)
	for i := range nodes {
		fk := nodes[i].PlayerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(player.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "player_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (abq *AuctionBidQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := abq.querySpec()
	_spec.Node.Columns = abq.ctx.Fields
	if len(abq.ctx.Fields) > 0 {
		_spec.Unique = abq.ctx.Unique != nil && *abq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, abq.driver, _spec)
}

func (abq *AuctionBidQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(auctionbid.Table, auctionbid.Columns, sqlgraph.NewFieldSpec(auctionbid.FieldID, field.TypeUUID))
	_spec.From = abq.sql
	if unique := abq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if abq.path != nil {
		_spec.Unique = true
	}
	if fields := abq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auctionbid.FieldID)
		for i := range fields {
			if fields[i] != auctionbid.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if abq.withAuction != nil {
			_spec.Node.AddColumnOnce(auctionbid.FieldAuctionID)
		}
		if abq.withPlayer != nil {
			_spec.Node.AddColumnOnce(auctionbid.FieldPlayerID)
		}
	}
	if ps := abq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := abq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := abq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := abq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (abq *AuctionBidQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(abq.driver.Dialect())
	t1 := builder.Table(auctionbid.Table)
	columns := abq.ctx.Fields
	if len(columns) == 0 {
		columns = auctionbid.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if abq.sql != nil {
		selector = abq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if abq.ctx.Unique != nil && *abq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range abq.predicates {
		p(selector)
	}
	for _, p := range abq.order {
		p(selector)
	}
	if offset := abq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := abq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuctionBidGroupBy is the group-by builder for AuctionBid entities.
type AuctionBidGroupBy struct {
	selector
	build *AuctionBidQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (abgb *AuctionBidGroupBy) Aggregate(fns ...AggregateFunc) *AuctionBidGroupBy {
	abgb.fns = append(abgb.fns, fns...)
	return abgb
}

// Scan applies the selector query and scans the result into the given value.
func (abgb *AuctionBidGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, abgb.build.ctx, ent.OpQueryGroupBy)
	if err := abgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuctionBidQuery, *AuctionBidGroupBy](ctx, abgb.build, abgb, abgb.build.inters, v)
}

func (abgb *AuctionBidGroupBy) sqlScan(ctx context.Context, root *AuctionBidQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(abgb.fns))
	for _, fn := range abgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*abgb.flds)+len(abgb.fns))
		for _, f := range *abgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*abgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := abgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuctionBidSelect is the builder for selecting fields of AuctionBid entities.
type AuctionBidSelect struct {
	*AuctionBidQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (abs *AuctionBidSelect) Aggregate(fns ...AggregateFunc) *AuctionBidSelect {
	abs.fns = append(abs.fns, fns...)
	return abs
}

// Scan applies the selector query and scans the result into the given value.
func (abs *AuctionBidSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, abs.ctx, ent.OpQuerySelect)
	if err := abs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuctionBidQuery, *AuctionBidSelect](ctx, abs.AuctionBidQuery, abs, abs.inters, v)
}

func (abs *AuctionBidSelect) sqlScan(ctx context.Context, root *AuctionBidQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(abs.fns))
	for _, fn := range abs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*abs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := abs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
