// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/card"
	"github.com/yyewolf/rwbyadv3/ent/cardstats"
	"github.com/yyewolf/rwbyadv3/ent/cardtype"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/schema"
)

// Card is the model entity for the Card schema.
type Card struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty,omitzero"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty,omitzero"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty,omitzero"`
	// PlayerID holds the value of the "player_id" field.
	PlayerID string `json:"player_id,omitempty,omitzero"`
	// CardType holds the value of the "card_type" field.
	CardType string `json:"card_type,omitempty,omitzero"`
	// Position holds the value of the "position" field.
	Position float64 `json:"position,omitempty,omitzero"`
	// Available holds the value of the "available" field.
	Available bool `json:"available,omitempty,omitzero"`
	// Level holds the value of the "level" field.
	Level int64 `json:"level,omitempty,omitzero"`
	// ExperiencePoints holds the value of the "experience_points" field.
	ExperiencePoints int64 `json:"experience_points,omitempty,omitzero"`
	// ExperiencePointsThreshold holds the value of the "experience_points_threshold" field.
	ExperiencePointsThreshold int64 `json:"experience_points_threshold,omitempty,omitzero"`
	// Rarity holds the value of the "rarity" field.
	Rarity int `json:"rarity,omitempty,omitzero"`
	// Buffs holds the value of the "buffs" field.
	Buffs int `json:"buffs,omitempty,omitzero"`
	// IndividualValue holds the value of the "individual_value" field.
	IndividualValue float64 `json:"individual_value,omitempty,omitzero"`
	// Metadata holds the value of the "metadata" field.
	Metadata schema.CardMetadata `json:"metadata,omitempty,omitzero"`
	// OwnedAt holds the value of the "owned_at" field.
	OwnedAt time.Time `json:"owned_at,omitempty,omitzero"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardQuery when eager-loading is set.
	Edges        CardEdges `json:"edges,omitempty,omitzero"`
	selectValues sql.SelectValues
}

// CardEdges holds the relations/edges for other nodes in the graph.
type CardEdges struct {
	// OwnedBy holds the value of the owned_by edge.
	OwnedBy *Player `json:"owned_by,omitempty,omitzero"`
	// InFavoritesOf holds the value of the in_favorites_of edge.
	InFavoritesOf []*Player `json:"in_favorites_of,omitempty,omitzero"`
	// InDeckOf holds the value of the in_deck_of edge.
	InDeckOf []*Player `json:"in_deck_of,omitempty,omitzero"`
	// Type holds the value of the type edge.
	Type *CardType `json:"type,omitempty,omitzero"`
	// Stats holds the value of the stats edge.
	Stats *CardStats `json:"stats,omitempty,omitzero"`
	// PlayerFavoriteCards holds the value of the player_favorite_cards edge.
	PlayerFavoriteCards []*PlayerFavoriteCards `json:"player_favorite_cards,omitempty,omitzero"`
	// PlayerDecks holds the value of the player_decks edge.
	PlayerDecks []*PlayerDeck `json:"player_decks,omitempty,omitzero"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// OwnedByOrErr returns the OwnedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) OwnedByOrErr() (*Player, error) {
	if e.OwnedBy != nil {
		return e.OwnedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "owned_by"}
}

// InFavoritesOfOrErr returns the InFavoritesOf value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) InFavoritesOfOrErr() ([]*Player, error) {
	if e.loadedTypes[1] {
		return e.InFavoritesOf, nil
	}
	return nil, &NotLoadedError{edge: "in_favorites_of"}
}

// InDeckOfOrErr returns the InDeckOf value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) InDeckOfOrErr() ([]*Player, error) {
	if e.loadedTypes[2] {
		return e.InDeckOf, nil
	}
	return nil, &NotLoadedError{edge: "in_deck_of"}
}

// TypeOrErr returns the Type value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) TypeOrErr() (*CardType, error) {
	if e.Type != nil {
		return e.Type, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: cardtype.Label}
	}
	return nil, &NotLoadedError{edge: "type"}
}

// StatsOrErr returns the Stats value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) StatsOrErr() (*CardStats, error) {
	if e.Stats != nil {
		return e.Stats, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: cardstats.Label}
	}
	return nil, &NotLoadedError{edge: "stats"}
}

// PlayerFavoriteCardsOrErr returns the PlayerFavoriteCards value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) PlayerFavoriteCardsOrErr() ([]*PlayerFavoriteCards, error) {
	if e.loadedTypes[5] {
		return e.PlayerFavoriteCards, nil
	}
	return nil, &NotLoadedError{edge: "player_favorite_cards"}
}

// PlayerDecksOrErr returns the PlayerDecks value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) PlayerDecksOrErr() ([]*PlayerDeck, error) {
	if e.loadedTypes[6] {
		return e.PlayerDecks, nil
	}
	return nil, &NotLoadedError{edge: "player_decks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Card) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case card.FieldMetadata:
			values[i] = new([]byte)
		case card.FieldAvailable:
			values[i] = new(sql.NullBool)
		case card.FieldPosition, card.FieldIndividualValue:
			values[i] = new(sql.NullFloat64)
		case card.FieldLevel, card.FieldExperiencePoints, card.FieldExperiencePointsThreshold, card.FieldRarity, card.FieldBuffs:
			values[i] = new(sql.NullInt64)
		case card.FieldPlayerID, card.FieldCardType:
			values[i] = new(sql.NullString)
		case card.FieldCreateTime, card.FieldUpdateTime, card.FieldOwnedAt:
			values[i] = new(sql.NullTime)
		case card.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Card fields.
func (c *Card) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case card.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				c.ID = *value
			}
		case card.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				c.CreateTime = value.Time
			}
		case card.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				c.UpdateTime = value.Time
			}
		case card.FieldPlayerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field player_id", values[i])
			} else if value.Valid {
				c.PlayerID = value.String
			}
		case card.FieldCardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field card_type", values[i])
			} else if value.Valid {
				c.CardType = value.String
			}
		case card.FieldPosition:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				c.Position = value.Float64
			}
		case card.FieldAvailable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field available", values[i])
			} else if value.Valid {
				c.Available = value.Bool
			}
		case card.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				c.Level = value.Int64
			}
		case card.FieldExperiencePoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field experience_points", values[i])
			} else if value.Valid {
				c.ExperiencePoints = value.Int64
			}
		case card.FieldExperiencePointsThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field experience_points_threshold", values[i])
			} else if value.Valid {
				c.ExperiencePointsThreshold = value.Int64
			}
		case card.FieldRarity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rarity", values[i])
			} else if value.Valid {
				c.Rarity = int(value.Int64)
			}
		case card.FieldBuffs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field buffs", values[i])
			} else if value.Valid {
				c.Buffs = int(value.Int64)
			}
		case card.FieldIndividualValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field individual_value", values[i])
			} else if value.Valid {
				c.IndividualValue = value.Float64
			}
		case card.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &c.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case card.FieldOwnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field owned_at", values[i])
			} else if value.Valid {
				c.OwnedAt = value.Time
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Card.
// This includes values selected through modifiers, order, etc.
func (c *Card) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryOwnedBy queries the "owned_by" edge of the Card entity.
func (c *Card) QueryOwnedBy() *PlayerQuery {
	return NewCardClient(c.config).QueryOwnedBy(c)
}

// QueryInFavoritesOf queries the "in_favorites_of" edge of the Card entity.
func (c *Card) QueryInFavoritesOf() *PlayerQuery {
	return NewCardClient(c.config).QueryInFavoritesOf(c)
}

// QueryInDeckOf queries the "in_deck_of" edge of the Card entity.
func (c *Card) QueryInDeckOf() *PlayerQuery {
	return NewCardClient(c.config).QueryInDeckOf(c)
}

// QueryType queries the "type" edge of the Card entity.
func (c *Card) QueryType() *CardTypeQuery {
	return NewCardClient(c.config).QueryType(c)
}

// QueryStats queries the "stats" edge of the Card entity.
func (c *Card) QueryStats() *CardStatsQuery {
	return NewCardClient(c.config).QueryStats(c)
}

// QueryPlayerFavoriteCards queries the "player_favorite_cards" edge of the Card entity.
func (c *Card) QueryPlayerFavoriteCards() *PlayerFavoriteCardsQuery {
	return NewCardClient(c.config).QueryPlayerFavoriteCards(c)
}

// QueryPlayerDecks queries the "player_decks" edge of the Card entity.
func (c *Card) QueryPlayerDecks() *PlayerDeckQuery {
	return NewCardClient(c.config).QueryPlayerDecks(c)
}

// Update returns a builder for updating this Card.
// Note that you need to call Card.Unwrap() before calling this method if this Card
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Card) Update() *CardUpdateOne {
	return NewCardClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Card entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Card) Unwrap() *Card {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Card is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Card) String() string {
	var builder strings.Builder
	builder.WriteString("Card(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("create_time=")
	builder.WriteString(c.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(c.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("player_id=")
	builder.WriteString(c.PlayerID)
	builder.WriteString(", ")
	builder.WriteString("card_type=")
	builder.WriteString(c.CardType)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", c.Position))
	builder.WriteString(", ")
	builder.WriteString("available=")
	builder.WriteString(fmt.Sprintf("%v", c.Available))
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", c.Level))
	builder.WriteString(", ")
	builder.WriteString("experience_points=")
	builder.WriteString(fmt.Sprintf("%v", c.ExperiencePoints))
	builder.WriteString(", ")
	builder.WriteString("experience_points_threshold=")
	builder.WriteString(fmt.Sprintf("%v", c.ExperiencePointsThreshold))
	builder.WriteString(", ")
	builder.WriteString("rarity=")
	builder.WriteString(fmt.Sprintf("%v", c.Rarity))
	builder.WriteString(", ")
	builder.WriteString("buffs=")
	builder.WriteString(fmt.Sprintf("%v", c.Buffs))
	builder.WriteString(", ")
	builder.WriteString("individual_value=")
	builder.WriteString(fmt.Sprintf("%v", c.IndividualValue))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", c.Metadata))
	builder.WriteString(", ")
	builder.WriteString("owned_at=")
	builder.WriteString(c.OwnedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Cards is a parsable slice of Card.
type Cards []*Card
