// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/rwbyadv3/ent/cookie"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
)

// CookieUpdate is the builder for updating Cookie entities.
type CookieUpdate struct {
	config
	hooks    []Hook
	mutation *CookieMutation
}

// Where appends a list predicates to the CookieUpdate builder.
func (cu *CookieUpdate) Where(ps ...predicate.Cookie) *CookieUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdateTime sets the "update_time" field.
func (cu *CookieUpdate) SetUpdateTime(t time.Time) *CookieUpdate {
	cu.mutation.SetUpdateTime(t)
	return cu
}

// SetPlayerID sets the "player_id" field.
func (cu *CookieUpdate) SetPlayerID(s string) *CookieUpdate {
	cu.mutation.SetPlayerID(s)
	return cu
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (cu *CookieUpdate) SetNillablePlayerID(s *string) *CookieUpdate {
	if s != nil {
		cu.SetPlayerID(*s)
	}
	return cu
}

// SetExpiresAt sets the "expires_at" field.
func (cu *CookieUpdate) SetExpiresAt(t time.Time) *CookieUpdate {
	cu.mutation.SetExpiresAt(t)
	return cu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (cu *CookieUpdate) SetNillableExpiresAt(t *time.Time) *CookieUpdate {
	if t != nil {
		cu.SetExpiresAt(*t)
	}
	return cu
}

// SetPlayer sets the "player" edge to the Player entity.
func (cu *CookieUpdate) SetPlayer(p *Player) *CookieUpdate {
	return cu.SetPlayerID(p.ID)
}

// Mutation returns the CookieMutation object of the builder.
func (cu *CookieUpdate) Mutation() *CookieMutation {
	return cu.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (cu *CookieUpdate) ClearPlayer() *CookieUpdate {
	cu.mutation.ClearPlayer()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CookieUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CookieUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CookieUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CookieUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CookieUpdate) defaults() {
	if _, ok := cu.mutation.UpdateTime(); !ok {
		v := cookie.UpdateDefaultUpdateTime()
		cu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CookieUpdate) check() error {
	if cu.mutation.PlayerCleared() && len(cu.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Cookie.player"`)
	}
	return nil
}

func (cu *CookieUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(cookie.Table, cookie.Columns, sqlgraph.NewFieldSpec(cookie.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdateTime(); ok {
		_spec.SetField(cookie.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cu.mutation.ExpiresAt(); ok {
		_spec.SetField(cookie.FieldExpiresAt, field.TypeTime, value)
	}
	if cu.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cookie.PlayerTable,
			Columns: []string{cookie.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cookie.PlayerTable,
			Columns: []string{cookie.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cookie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CookieUpdateOne is the builder for updating a single Cookie entity.
type CookieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CookieMutation
}

// SetUpdateTime sets the "update_time" field.
func (cuo *CookieUpdateOne) SetUpdateTime(t time.Time) *CookieUpdateOne {
	cuo.mutation.SetUpdateTime(t)
	return cuo
}

// SetPlayerID sets the "player_id" field.
func (cuo *CookieUpdateOne) SetPlayerID(s string) *CookieUpdateOne {
	cuo.mutation.SetPlayerID(s)
	return cuo
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (cuo *CookieUpdateOne) SetNillablePlayerID(s *string) *CookieUpdateOne {
	if s != nil {
		cuo.SetPlayerID(*s)
	}
	return cuo
}

// SetExpiresAt sets the "expires_at" field.
func (cuo *CookieUpdateOne) SetExpiresAt(t time.Time) *CookieUpdateOne {
	cuo.mutation.SetExpiresAt(t)
	return cuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (cuo *CookieUpdateOne) SetNillableExpiresAt(t *time.Time) *CookieUpdateOne {
	if t != nil {
		cuo.SetExpiresAt(*t)
	}
	return cuo
}

// SetPlayer sets the "player" edge to the Player entity.
func (cuo *CookieUpdateOne) SetPlayer(p *Player) *CookieUpdateOne {
	return cuo.SetPlayerID(p.ID)
}

// Mutation returns the CookieMutation object of the builder.
func (cuo *CookieUpdateOne) Mutation() *CookieMutation {
	return cuo.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (cuo *CookieUpdateOne) ClearPlayer() *CookieUpdateOne {
	cuo.mutation.ClearPlayer()
	return cuo
}

// Where appends a list predicates to the CookieUpdate builder.
func (cuo *CookieUpdateOne) Where(ps ...predicate.Cookie) *CookieUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CookieUpdateOne) Select(field string, fields ...string) *CookieUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Cookie entity.
func (cuo *CookieUpdateOne) Save(ctx context.Context) (*Cookie, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CookieUpdateOne) SaveX(ctx context.Context) *Cookie {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CookieUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CookieUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CookieUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdateTime(); !ok {
		v := cookie.UpdateDefaultUpdateTime()
		cuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CookieUpdateOne) check() error {
	if cuo.mutation.PlayerCleared() && len(cuo.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Cookie.player"`)
	}
	return nil
}

func (cuo *CookieUpdateOne) sqlSave(ctx context.Context) (_node *Cookie, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cookie.Table, cookie.Columns, sqlgraph.NewFieldSpec(cookie.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cookie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cookie.FieldID)
		for _, f := range fields {
			if !cookie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cookie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdateTime(); ok {
		_spec.SetField(cookie.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.ExpiresAt(); ok {
		_spec.SetField(cookie.FieldExpiresAt, field.TypeTime, value)
	}
	if cuo.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cookie.PlayerTable,
			Columns: []string{cookie.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cookie.PlayerTable,
			Columns: []string{cookie.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cookie{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cookie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
