// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/rwbyadv3/ent/daily"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
)

// DailyUpdate is the builder for updating Daily entities.
type DailyUpdate struct {
	config
	hooks    []Hook
	mutation *DailyMutation
}

// Where appends a list predicates to the DailyUpdate builder.
func (du *DailyUpdate) Where(ps ...predicate.Daily) *DailyUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetUpdateTime sets the "update_time" field.
func (du *DailyUpdate) SetUpdateTime(t time.Time) *DailyUpdate {
	du.mutation.SetUpdateTime(t)
	return du
}

// SetPlayerID sets the "player_id" field.
func (du *DailyUpdate) SetPlayerID(s string) *DailyUpdate {
	du.mutation.SetPlayerID(s)
	return du
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (du *DailyUpdate) SetNillablePlayerID(s *string) *DailyUpdate {
	if s != nil {
		du.SetPlayerID(*s)
	}
	return du
}

// SetHasVoted sets the "has_voted" field.
func (du *DailyUpdate) SetHasVoted(b bool) *DailyUpdate {
	du.mutation.SetHasVoted(b)
	return du
}

// SetNillableHasVoted sets the "has_voted" field if the given value is not nil.
func (du *DailyUpdate) SetNillableHasVoted(b *bool) *DailyUpdate {
	if b != nil {
		du.SetHasVoted(*b)
	}
	return du
}

// SetLastVoteAt sets the "last_vote_at" field.
func (du *DailyUpdate) SetLastVoteAt(t time.Time) *DailyUpdate {
	du.mutation.SetLastVoteAt(t)
	return du
}

// SetNillableLastVoteAt sets the "last_vote_at" field if the given value is not nil.
func (du *DailyUpdate) SetNillableLastVoteAt(t *time.Time) *DailyUpdate {
	if t != nil {
		du.SetLastVoteAt(*t)
	}
	return du
}

// SetStreak sets the "streak" field.
func (du *DailyUpdate) SetStreak(i int64) *DailyUpdate {
	du.mutation.ResetStreak()
	du.mutation.SetStreak(i)
	return du
}

// SetNillableStreak sets the "streak" field if the given value is not nil.
func (du *DailyUpdate) SetNillableStreak(i *int64) *DailyUpdate {
	if i != nil {
		du.SetStreak(*i)
	}
	return du
}

// AddStreak adds i to the "streak" field.
func (du *DailyUpdate) AddStreak(i int64) *DailyUpdate {
	du.mutation.AddStreak(i)
	return du
}

// SetOfID sets the "of" edge to the Player entity by ID.
func (du *DailyUpdate) SetOfID(id string) *DailyUpdate {
	du.mutation.SetOfID(id)
	return du
}

// SetOf sets the "of" edge to the Player entity.
func (du *DailyUpdate) SetOf(p *Player) *DailyUpdate {
	return du.SetOfID(p.ID)
}

// Mutation returns the DailyMutation object of the builder.
func (du *DailyUpdate) Mutation() *DailyMutation {
	return du.mutation
}

// ClearOf clears the "of" edge to the Player entity.
func (du *DailyUpdate) ClearOf() *DailyUpdate {
	du.mutation.ClearOf()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DailyUpdate) Save(ctx context.Context) (int, error) {
	du.defaults()
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DailyUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DailyUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DailyUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DailyUpdate) defaults() {
	if _, ok := du.mutation.UpdateTime(); !ok {
		v := daily.UpdateDefaultUpdateTime()
		du.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DailyUpdate) check() error {
	if du.mutation.OfCleared() && len(du.mutation.OfIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Daily.of"`)
	}
	return nil
}

func (du *DailyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(daily.Table, daily.Columns, sqlgraph.NewFieldSpec(daily.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.UpdateTime(); ok {
		_spec.SetField(daily.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := du.mutation.HasVoted(); ok {
		_spec.SetField(daily.FieldHasVoted, field.TypeBool, value)
	}
	if value, ok := du.mutation.LastVoteAt(); ok {
		_spec.SetField(daily.FieldLastVoteAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.Streak(); ok {
		_spec.SetField(daily.FieldStreak, field.TypeInt64, value)
	}
	if value, ok := du.mutation.AddedStreak(); ok {
		_spec.AddField(daily.FieldStreak, field.TypeInt64, value)
	}
	if du.mutation.OfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   daily.OfTable,
			Columns: []string{daily.OfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.OfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   daily.OfTable,
			Columns: []string{daily.OfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{daily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DailyUpdateOne is the builder for updating a single Daily entity.
type DailyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyMutation
}

// SetUpdateTime sets the "update_time" field.
func (duo *DailyUpdateOne) SetUpdateTime(t time.Time) *DailyUpdateOne {
	duo.mutation.SetUpdateTime(t)
	return duo
}

// SetPlayerID sets the "player_id" field.
func (duo *DailyUpdateOne) SetPlayerID(s string) *DailyUpdateOne {
	duo.mutation.SetPlayerID(s)
	return duo
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (duo *DailyUpdateOne) SetNillablePlayerID(s *string) *DailyUpdateOne {
	if s != nil {
		duo.SetPlayerID(*s)
	}
	return duo
}

// SetHasVoted sets the "has_voted" field.
func (duo *DailyUpdateOne) SetHasVoted(b bool) *DailyUpdateOne {
	duo.mutation.SetHasVoted(b)
	return duo
}

// SetNillableHasVoted sets the "has_voted" field if the given value is not nil.
func (duo *DailyUpdateOne) SetNillableHasVoted(b *bool) *DailyUpdateOne {
	if b != nil {
		duo.SetHasVoted(*b)
	}
	return duo
}

// SetLastVoteAt sets the "last_vote_at" field.
func (duo *DailyUpdateOne) SetLastVoteAt(t time.Time) *DailyUpdateOne {
	duo.mutation.SetLastVoteAt(t)
	return duo
}

// SetNillableLastVoteAt sets the "last_vote_at" field if the given value is not nil.
func (duo *DailyUpdateOne) SetNillableLastVoteAt(t *time.Time) *DailyUpdateOne {
	if t != nil {
		duo.SetLastVoteAt(*t)
	}
	return duo
}

// SetStreak sets the "streak" field.
func (duo *DailyUpdateOne) SetStreak(i int64) *DailyUpdateOne {
	duo.mutation.ResetStreak()
	duo.mutation.SetStreak(i)
	return duo
}

// SetNillableStreak sets the "streak" field if the given value is not nil.
func (duo *DailyUpdateOne) SetNillableStreak(i *int64) *DailyUpdateOne {
	if i != nil {
		duo.SetStreak(*i)
	}
	return duo
}

// AddStreak adds i to the "streak" field.
func (duo *DailyUpdateOne) AddStreak(i int64) *DailyUpdateOne {
	duo.mutation.AddStreak(i)
	return duo
}

// SetOfID sets the "of" edge to the Player entity by ID.
func (duo *DailyUpdateOne) SetOfID(id string) *DailyUpdateOne {
	duo.mutation.SetOfID(id)
	return duo
}

// SetOf sets the "of" edge to the Player entity.
func (duo *DailyUpdateOne) SetOf(p *Player) *DailyUpdateOne {
	return duo.SetOfID(p.ID)
}

// Mutation returns the DailyMutation object of the builder.
func (duo *DailyUpdateOne) Mutation() *DailyMutation {
	return duo.mutation
}

// ClearOf clears the "of" edge to the Player entity.
func (duo *DailyUpdateOne) ClearOf() *DailyUpdateOne {
	duo.mutation.ClearOf()
	return duo
}

// Where appends a list predicates to the DailyUpdate builder.
func (duo *DailyUpdateOne) Where(ps ...predicate.Daily) *DailyUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DailyUpdateOne) Select(field string, fields ...string) *DailyUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Daily entity.
func (duo *DailyUpdateOne) Save(ctx context.Context) (*Daily, error) {
	duo.defaults()
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DailyUpdateOne) SaveX(ctx context.Context) *Daily {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DailyUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DailyUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DailyUpdateOne) defaults() {
	if _, ok := duo.mutation.UpdateTime(); !ok {
		v := daily.UpdateDefaultUpdateTime()
		duo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DailyUpdateOne) check() error {
	if duo.mutation.OfCleared() && len(duo.mutation.OfIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Daily.of"`)
	}
	return nil
}

func (duo *DailyUpdateOne) sqlSave(ctx context.Context) (_node *Daily, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(daily.Table, daily.Columns, sqlgraph.NewFieldSpec(daily.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Daily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, daily.FieldID)
		for _, f := range fields {
			if !daily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != daily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.UpdateTime(); ok {
		_spec.SetField(daily.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := duo.mutation.HasVoted(); ok {
		_spec.SetField(daily.FieldHasVoted, field.TypeBool, value)
	}
	if value, ok := duo.mutation.LastVoteAt(); ok {
		_spec.SetField(daily.FieldLastVoteAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.Streak(); ok {
		_spec.SetField(daily.FieldStreak, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.AddedStreak(); ok {
		_spec.AddField(daily.FieldStreak, field.TypeInt64, value)
	}
	if duo.mutation.OfCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   daily.OfTable,
			Columns: []string{daily.OfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.OfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   daily.OfTable,
			Columns: []string{daily.OfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Daily{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{daily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
