// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/rwbyadv3/ent/daily"
	"github.com/yyewolf/rwbyadv3/ent/player"
)

// DailyCreate is the builder for creating a Daily entity.
type DailyCreate struct {
	config
	mutation *DailyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (dc *DailyCreate) SetCreateTime(t time.Time) *DailyCreate {
	dc.mutation.SetCreateTime(t)
	return dc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (dc *DailyCreate) SetNillableCreateTime(t *time.Time) *DailyCreate {
	if t != nil {
		dc.SetCreateTime(*t)
	}
	return dc
}

// SetUpdateTime sets the "update_time" field.
func (dc *DailyCreate) SetUpdateTime(t time.Time) *DailyCreate {
	dc.mutation.SetUpdateTime(t)
	return dc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (dc *DailyCreate) SetNillableUpdateTime(t *time.Time) *DailyCreate {
	if t != nil {
		dc.SetUpdateTime(*t)
	}
	return dc
}

// SetPlayerID sets the "player_id" field.
func (dc *DailyCreate) SetPlayerID(s string) *DailyCreate {
	dc.mutation.SetPlayerID(s)
	return dc
}

// SetHasVoted sets the "has_voted" field.
func (dc *DailyCreate) SetHasVoted(b bool) *DailyCreate {
	dc.mutation.SetHasVoted(b)
	return dc
}

// SetNillableHasVoted sets the "has_voted" field if the given value is not nil.
func (dc *DailyCreate) SetNillableHasVoted(b *bool) *DailyCreate {
	if b != nil {
		dc.SetHasVoted(*b)
	}
	return dc
}

// SetLastVoteAt sets the "last_vote_at" field.
func (dc *DailyCreate) SetLastVoteAt(t time.Time) *DailyCreate {
	dc.mutation.SetLastVoteAt(t)
	return dc
}

// SetNillableLastVoteAt sets the "last_vote_at" field if the given value is not nil.
func (dc *DailyCreate) SetNillableLastVoteAt(t *time.Time) *DailyCreate {
	if t != nil {
		dc.SetLastVoteAt(*t)
	}
	return dc
}

// SetStreak sets the "streak" field.
func (dc *DailyCreate) SetStreak(i int64) *DailyCreate {
	dc.mutation.SetStreak(i)
	return dc
}

// SetNillableStreak sets the "streak" field if the given value is not nil.
func (dc *DailyCreate) SetNillableStreak(i *int64) *DailyCreate {
	if i != nil {
		dc.SetStreak(*i)
	}
	return dc
}

// SetOfID sets the "of" edge to the Player entity by ID.
func (dc *DailyCreate) SetOfID(id string) *DailyCreate {
	dc.mutation.SetOfID(id)
	return dc
}

// SetOf sets the "of" edge to the Player entity.
func (dc *DailyCreate) SetOf(p *Player) *DailyCreate {
	return dc.SetOfID(p.ID)
}

// Mutation returns the DailyMutation object of the builder.
func (dc *DailyCreate) Mutation() *DailyMutation {
	return dc.mutation
}

// Save creates the Daily in the database.
func (dc *DailyCreate) Save(ctx context.Context) (*Daily, error) {
	dc.defaults()
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DailyCreate) SaveX(ctx context.Context) *Daily {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DailyCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DailyCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dc *DailyCreate) defaults() {
	if _, ok := dc.mutation.CreateTime(); !ok {
		v := daily.DefaultCreateTime()
		dc.mutation.SetCreateTime(v)
	}
	if _, ok := dc.mutation.UpdateTime(); !ok {
		v := daily.DefaultUpdateTime()
		dc.mutation.SetUpdateTime(v)
	}
	if _, ok := dc.mutation.HasVoted(); !ok {
		v := daily.DefaultHasVoted
		dc.mutation.SetHasVoted(v)
	}
	if _, ok := dc.mutation.LastVoteAt(); !ok {
		v := daily.DefaultLastVoteAt()
		dc.mutation.SetLastVoteAt(v)
	}
	if _, ok := dc.mutation.Streak(); !ok {
		v := daily.DefaultStreak
		dc.mutation.SetStreak(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DailyCreate) check() error {
	if _, ok := dc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Daily.create_time"`)}
	}
	if _, ok := dc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Daily.update_time"`)}
	}
	if _, ok := dc.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player_id", err: errors.New(`ent: missing required field "Daily.player_id"`)}
	}
	if _, ok := dc.mutation.HasVoted(); !ok {
		return &ValidationError{Name: "has_voted", err: errors.New(`ent: missing required field "Daily.has_voted"`)}
	}
	if _, ok := dc.mutation.LastVoteAt(); !ok {
		return &ValidationError{Name: "last_vote_at", err: errors.New(`ent: missing required field "Daily.last_vote_at"`)}
	}
	if _, ok := dc.mutation.Streak(); !ok {
		return &ValidationError{Name: "streak", err: errors.New(`ent: missing required field "Daily.streak"`)}
	}
	if len(dc.mutation.OfIDs()) == 0 {
		return &ValidationError{Name: "of", err: errors.New(`ent: missing required edge "Daily.of"`)}
	}
	return nil
}

func (dc *DailyCreate) sqlSave(ctx context.Context) (*Daily, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DailyCreate) createSpec() (*Daily, *sqlgraph.CreateSpec) {
	var (
		_node = &Daily{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(daily.Table, sqlgraph.NewFieldSpec(daily.FieldID, field.TypeInt))
	)
	_spec.OnConflict = dc.conflict
	if value, ok := dc.mutation.CreateTime(); ok {
		_spec.SetField(daily.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := dc.mutation.UpdateTime(); ok {
		_spec.SetField(daily.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := dc.mutation.HasVoted(); ok {
		_spec.SetField(daily.FieldHasVoted, field.TypeBool, value)
		_node.HasVoted = value
	}
	if value, ok := dc.mutation.LastVoteAt(); ok {
		_spec.SetField(daily.FieldLastVoteAt, field.TypeTime, value)
		_node.LastVoteAt = value
	}
	if value, ok := dc.mutation.Streak(); ok {
		_spec.SetField(daily.FieldStreak, field.TypeInt64, value)
		_node.Streak = value
	}
	if nodes := dc.mutation.OfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   daily.OfTable,
			Columns: []string{daily.OfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Daily.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (dc *DailyCreate) OnConflict(opts ...sql.ConflictOption) *DailyUpsertOne {
	dc.conflict = opts
	return &DailyUpsertOne{
		create: dc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Daily.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dc *DailyCreate) OnConflictColumns(columns ...string) *DailyUpsertOne {
	dc.conflict = append(dc.conflict, sql.ConflictColumns(columns...))
	return &DailyUpsertOne{
		create: dc,
	}
}

type (
	// DailyUpsertOne is the builder for "upsert"-ing
	//  one Daily node.
	DailyUpsertOne struct {
		create *DailyCreate
	}

	// DailyUpsert is the "OnConflict" setter.
	DailyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *DailyUpsert) SetUpdateTime(v time.Time) *DailyUpsert {
	u.Set(daily.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DailyUpsert) UpdateUpdateTime() *DailyUpsert {
	u.SetExcluded(daily.FieldUpdateTime)
	return u
}

// SetPlayerID sets the "player_id" field.
func (u *DailyUpsert) SetPlayerID(v string) *DailyUpsert {
	u.Set(daily.FieldPlayerID, v)
	return u
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *DailyUpsert) UpdatePlayerID() *DailyUpsert {
	u.SetExcluded(daily.FieldPlayerID)
	return u
}

// SetHasVoted sets the "has_voted" field.
func (u *DailyUpsert) SetHasVoted(v bool) *DailyUpsert {
	u.Set(daily.FieldHasVoted, v)
	return u
}

// UpdateHasVoted sets the "has_voted" field to the value that was provided on create.
func (u *DailyUpsert) UpdateHasVoted() *DailyUpsert {
	u.SetExcluded(daily.FieldHasVoted)
	return u
}

// SetLastVoteAt sets the "last_vote_at" field.
func (u *DailyUpsert) SetLastVoteAt(v time.Time) *DailyUpsert {
	u.Set(daily.FieldLastVoteAt, v)
	return u
}

// UpdateLastVoteAt sets the "last_vote_at" field to the value that was provided on create.
func (u *DailyUpsert) UpdateLastVoteAt() *DailyUpsert {
	u.SetExcluded(daily.FieldLastVoteAt)
	return u
}

// SetStreak sets the "streak" field.
func (u *DailyUpsert) SetStreak(v int64) *DailyUpsert {
	u.Set(daily.FieldStreak, v)
	return u
}

// UpdateStreak sets the "streak" field to the value that was provided on create.
func (u *DailyUpsert) UpdateStreak() *DailyUpsert {
	u.SetExcluded(daily.FieldStreak)
	return u
}

// AddStreak adds v to the "streak" field.
func (u *DailyUpsert) AddStreak(v int64) *DailyUpsert {
	u.Add(daily.FieldStreak, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Daily.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyUpsertOne) UpdateNewValues() *DailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(daily.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Daily.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DailyUpsertOne) Ignore() *DailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyUpsertOne) DoNothing() *DailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyCreate.OnConflict
// documentation for more info.
func (u *DailyUpsertOne) Update(set func(*DailyUpsert)) *DailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DailyUpsertOne) SetUpdateTime(v time.Time) *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DailyUpsertOne) UpdateUpdateTime() *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetPlayerID sets the "player_id" field.
func (u *DailyUpsertOne) SetPlayerID(v string) *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.SetPlayerID(v)
	})
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *DailyUpsertOne) UpdatePlayerID() *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.UpdatePlayerID()
	})
}

// SetHasVoted sets the "has_voted" field.
func (u *DailyUpsertOne) SetHasVoted(v bool) *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.SetHasVoted(v)
	})
}

// UpdateHasVoted sets the "has_voted" field to the value that was provided on create.
func (u *DailyUpsertOne) UpdateHasVoted() *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateHasVoted()
	})
}

// SetLastVoteAt sets the "last_vote_at" field.
func (u *DailyUpsertOne) SetLastVoteAt(v time.Time) *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.SetLastVoteAt(v)
	})
}

// UpdateLastVoteAt sets the "last_vote_at" field to the value that was provided on create.
func (u *DailyUpsertOne) UpdateLastVoteAt() *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateLastVoteAt()
	})
}

// SetStreak sets the "streak" field.
func (u *DailyUpsertOne) SetStreak(v int64) *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.SetStreak(v)
	})
}

// AddStreak adds v to the "streak" field.
func (u *DailyUpsertOne) AddStreak(v int64) *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.AddStreak(v)
	})
}

// UpdateStreak sets the "streak" field to the value that was provided on create.
func (u *DailyUpsertOne) UpdateStreak() *DailyUpsertOne {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateStreak()
	})
}

// Exec executes the query.
func (u *DailyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DailyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DailyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DailyCreateBulk is the builder for creating many Daily entities in bulk.
type DailyCreateBulk struct {
	config
	err      error
	builders []*DailyCreate
	conflict []sql.ConflictOption
}

// Save creates the Daily entities in the database.
func (dcb *DailyCreateBulk) Save(ctx context.Context) ([]*Daily, error) {
	if dcb.err != nil {
		return nil, dcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Daily, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DailyCreateBulk) SaveX(ctx context.Context) []*Daily {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DailyCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DailyCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Daily.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (dcb *DailyCreateBulk) OnConflict(opts ...sql.ConflictOption) *DailyUpsertBulk {
	dcb.conflict = opts
	return &DailyUpsertBulk{
		create: dcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Daily.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dcb *DailyCreateBulk) OnConflictColumns(columns ...string) *DailyUpsertBulk {
	dcb.conflict = append(dcb.conflict, sql.ConflictColumns(columns...))
	return &DailyUpsertBulk{
		create: dcb,
	}
}

// DailyUpsertBulk is the builder for "upsert"-ing
// a bulk of Daily nodes.
type DailyUpsertBulk struct {
	create *DailyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Daily.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyUpsertBulk) UpdateNewValues() *DailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(daily.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Daily.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DailyUpsertBulk) Ignore() *DailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyUpsertBulk) DoNothing() *DailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyCreateBulk.OnConflict
// documentation for more info.
func (u *DailyUpsertBulk) Update(set func(*DailyUpsert)) *DailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DailyUpsertBulk) SetUpdateTime(v time.Time) *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DailyUpsertBulk) UpdateUpdateTime() *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetPlayerID sets the "player_id" field.
func (u *DailyUpsertBulk) SetPlayerID(v string) *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.SetPlayerID(v)
	})
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *DailyUpsertBulk) UpdatePlayerID() *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.UpdatePlayerID()
	})
}

// SetHasVoted sets the "has_voted" field.
func (u *DailyUpsertBulk) SetHasVoted(v bool) *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.SetHasVoted(v)
	})
}

// UpdateHasVoted sets the "has_voted" field to the value that was provided on create.
func (u *DailyUpsertBulk) UpdateHasVoted() *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateHasVoted()
	})
}

// SetLastVoteAt sets the "last_vote_at" field.
func (u *DailyUpsertBulk) SetLastVoteAt(v time.Time) *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.SetLastVoteAt(v)
	})
}

// UpdateLastVoteAt sets the "last_vote_at" field to the value that was provided on create.
func (u *DailyUpsertBulk) UpdateLastVoteAt() *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateLastVoteAt()
	})
}

// SetStreak sets the "streak" field.
func (u *DailyUpsertBulk) SetStreak(v int64) *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.SetStreak(v)
	})
}

// AddStreak adds v to the "streak" field.
func (u *DailyUpsertBulk) AddStreak(v int64) *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.AddStreak(v)
	})
}

// UpdateStreak sets the "streak" field to the value that was provided on create.
func (u *DailyUpsertBulk) UpdateStreak() *DailyUpsertBulk {
	return u.Update(func(s *DailyUpsert) {
		s.UpdateStreak()
	})
}

// Exec executes the query.
func (u *DailyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DailyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
