// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/dungeon"
	"github.com/yyewolf/rwbyadv3/ent/player"
)

// Dungeon is the model entity for the Dungeon schema.
type Dungeon struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// PlayerID holds the value of the "player_id" field.
	PlayerID string `json:"player_id,omitempty"`
	// Seed holds the value of the "seed" field.
	Seed int64 `json:"seed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DungeonQuery when eager-loading is set.
	Edges        DungeonEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DungeonEdges holds the relations/edges for other nodes in the graph.
type DungeonEdges struct {
	// OwnedBy holds the value of the owned_by edge.
	OwnedBy *Player `json:"owned_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnedByOrErr returns the OwnedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DungeonEdges) OwnedByOrErr() (*Player, error) {
	if e.OwnedBy != nil {
		return e.OwnedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "owned_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dungeon) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dungeon.FieldSeed:
			values[i] = new(sql.NullInt64)
		case dungeon.FieldPlayerID:
			values[i] = new(sql.NullString)
		case dungeon.FieldCreateTime, dungeon.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case dungeon.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dungeon fields.
func (d *Dungeon) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dungeon.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				d.ID = *value
			}
		case dungeon.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				d.CreateTime = value.Time
			}
		case dungeon.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				d.UpdateTime = value.Time
			}
		case dungeon.FieldPlayerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field player_id", values[i])
			} else if value.Valid {
				d.PlayerID = value.String
			}
		case dungeon.FieldSeed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seed", values[i])
			} else if value.Valid {
				d.Seed = value.Int64
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Dungeon.
// This includes values selected through modifiers, order, etc.
func (d *Dungeon) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryOwnedBy queries the "owned_by" edge of the Dungeon entity.
func (d *Dungeon) QueryOwnedBy() *PlayerQuery {
	return NewDungeonClient(d.config).QueryOwnedBy(d)
}

// Update returns a builder for updating this Dungeon.
// Note that you need to call Dungeon.Unwrap() before calling this method if this Dungeon
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Dungeon) Update() *DungeonUpdateOne {
	return NewDungeonClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Dungeon entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Dungeon) Unwrap() *Dungeon {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dungeon is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Dungeon) String() string {
	var builder strings.Builder
	builder.WriteString("Dungeon(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("create_time=")
	builder.WriteString(d.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(d.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("player_id=")
	builder.WriteString(d.PlayerID)
	builder.WriteString(", ")
	builder.WriteString("seed=")
	builder.WriteString(fmt.Sprintf("%v", d.Seed))
	builder.WriteByte(')')
	return builder.String()
}

// Dungeons is a parsable slice of Dungeon.
type Dungeons []*Dungeon
