// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/card"
	"github.com/yyewolf/rwbyadv3/ent/listing"
	"github.com/yyewolf/rwbyadv3/ent/player"
)

// ListingCreate is the builder for creating a Listing entity.
type ListingCreate struct {
	config
	mutation *ListingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (lc *ListingCreate) SetCreateTime(t time.Time) *ListingCreate {
	lc.mutation.SetCreateTime(t)
	return lc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (lc *ListingCreate) SetNillableCreateTime(t *time.Time) *ListingCreate {
	if t != nil {
		lc.SetCreateTime(*t)
	}
	return lc
}

// SetUpdateTime sets the "update_time" field.
func (lc *ListingCreate) SetUpdateTime(t time.Time) *ListingCreate {
	lc.mutation.SetUpdateTime(t)
	return lc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (lc *ListingCreate) SetNillableUpdateTime(t *time.Time) *ListingCreate {
	if t != nil {
		lc.SetUpdateTime(*t)
	}
	return lc
}

// SetPlayerID sets the "player_id" field.
func (lc *ListingCreate) SetPlayerID(s string) *ListingCreate {
	lc.mutation.SetPlayerID(s)
	return lc
}

// SetCardID sets the "card_id" field.
func (lc *ListingCreate) SetCardID(u uuid.UUID) *ListingCreate {
	lc.mutation.SetCardID(u)
	return lc
}

// SetPrice sets the "price" field.
func (lc *ListingCreate) SetPrice(i int64) *ListingCreate {
	lc.mutation.SetPrice(i)
	return lc
}

// SetNote sets the "note" field.
func (lc *ListingCreate) SetNote(s string) *ListingCreate {
	lc.mutation.SetNote(s)
	return lc
}

// SetID sets the "id" field.
func (lc *ListingCreate) SetID(u uuid.UUID) *ListingCreate {
	lc.mutation.SetID(u)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *ListingCreate) SetNillableID(u *uuid.UUID) *ListingCreate {
	if u != nil {
		lc.SetID(*u)
	}
	return lc
}

// SetOwnedByID sets the "owned_by" edge to the Player entity by ID.
func (lc *ListingCreate) SetOwnedByID(id string) *ListingCreate {
	lc.mutation.SetOwnedByID(id)
	return lc
}

// SetOwnedBy sets the "owned_by" edge to the Player entity.
func (lc *ListingCreate) SetOwnedBy(p *Player) *ListingCreate {
	return lc.SetOwnedByID(p.ID)
}

// SetCard sets the "card" edge to the Card entity.
func (lc *ListingCreate) SetCard(c *Card) *ListingCreate {
	return lc.SetCardID(c.ID)
}

// Mutation returns the ListingMutation object of the builder.
func (lc *ListingCreate) Mutation() *ListingMutation {
	return lc.mutation
}

// Save creates the Listing in the database.
func (lc *ListingCreate) Save(ctx context.Context) (*Listing, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *ListingCreate) SaveX(ctx context.Context) *Listing {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *ListingCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *ListingCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *ListingCreate) defaults() {
	if _, ok := lc.mutation.CreateTime(); !ok {
		v := listing.DefaultCreateTime()
		lc.mutation.SetCreateTime(v)
	}
	if _, ok := lc.mutation.UpdateTime(); !ok {
		v := listing.DefaultUpdateTime()
		lc.mutation.SetUpdateTime(v)
	}
	if _, ok := lc.mutation.ID(); !ok {
		v := listing.DefaultID()
		lc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *ListingCreate) check() error {
	if _, ok := lc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Listing.create_time"`)}
	}
	if _, ok := lc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Listing.update_time"`)}
	}
	if _, ok := lc.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player_id", err: errors.New(`ent: missing required field "Listing.player_id"`)}
	}
	if _, ok := lc.mutation.CardID(); !ok {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: missing required field "Listing.card_id"`)}
	}
	if _, ok := lc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Listing.price"`)}
	}
	if v, ok := lc.mutation.Price(); ok {
		if err := listing.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Listing.price": %w`, err)}
		}
	}
	if _, ok := lc.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "Listing.note"`)}
	}
	if len(lc.mutation.OwnedByIDs()) == 0 {
		return &ValidationError{Name: "owned_by", err: errors.New(`ent: missing required edge "Listing.owned_by"`)}
	}
	if len(lc.mutation.CardIDs()) == 0 {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "Listing.card"`)}
	}
	return nil
}

func (lc *ListingCreate) sqlSave(ctx context.Context) (*Listing, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *ListingCreate) createSpec() (*Listing, *sqlgraph.CreateSpec) {
	var (
		_node = &Listing{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(listing.Table, sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = lc.conflict
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := lc.mutation.CreateTime(); ok {
		_spec.SetField(listing.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := lc.mutation.UpdateTime(); ok {
		_spec.SetField(listing.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := lc.mutation.Price(); ok {
		_spec.SetField(listing.FieldPrice, field.TypeInt64, value)
		_node.Price = value
	}
	if value, ok := lc.mutation.Note(); ok {
		_spec.SetField(listing.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := lc.mutation.OwnedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.OwnedByTable,
			Columns: []string{listing.OwnedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   listing.CardTable,
			Columns: []string{listing.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Listing.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ListingUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (lc *ListingCreate) OnConflict(opts ...sql.ConflictOption) *ListingUpsertOne {
	lc.conflict = opts
	return &ListingUpsertOne{
		create: lc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Listing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (lc *ListingCreate) OnConflictColumns(columns ...string) *ListingUpsertOne {
	lc.conflict = append(lc.conflict, sql.ConflictColumns(columns...))
	return &ListingUpsertOne{
		create: lc,
	}
}

type (
	// ListingUpsertOne is the builder for "upsert"-ing
	//  one Listing node.
	ListingUpsertOne struct {
		create *ListingCreate
	}

	// ListingUpsert is the "OnConflict" setter.
	ListingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *ListingUpsert) SetUpdateTime(v time.Time) *ListingUpsert {
	u.Set(listing.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ListingUpsert) UpdateUpdateTime() *ListingUpsert {
	u.SetExcluded(listing.FieldUpdateTime)
	return u
}

// SetPlayerID sets the "player_id" field.
func (u *ListingUpsert) SetPlayerID(v string) *ListingUpsert {
	u.Set(listing.FieldPlayerID, v)
	return u
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *ListingUpsert) UpdatePlayerID() *ListingUpsert {
	u.SetExcluded(listing.FieldPlayerID)
	return u
}

// SetCardID sets the "card_id" field.
func (u *ListingUpsert) SetCardID(v uuid.UUID) *ListingUpsert {
	u.Set(listing.FieldCardID, v)
	return u
}

// UpdateCardID sets the "card_id" field to the value that was provided on create.
func (u *ListingUpsert) UpdateCardID() *ListingUpsert {
	u.SetExcluded(listing.FieldCardID)
	return u
}

// SetPrice sets the "price" field.
func (u *ListingUpsert) SetPrice(v int64) *ListingUpsert {
	u.Set(listing.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ListingUpsert) UpdatePrice() *ListingUpsert {
	u.SetExcluded(listing.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *ListingUpsert) AddPrice(v int64) *ListingUpsert {
	u.Add(listing.FieldPrice, v)
	return u
}

// SetNote sets the "note" field.
func (u *ListingUpsert) SetNote(v string) *ListingUpsert {
	u.Set(listing.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ListingUpsert) UpdateNote() *ListingUpsert {
	u.SetExcluded(listing.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Listing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(listing.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ListingUpsertOne) UpdateNewValues() *ListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(listing.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(listing.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Listing.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ListingUpsertOne) Ignore() *ListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ListingUpsertOne) DoNothing() *ListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ListingCreate.OnConflict
// documentation for more info.
func (u *ListingUpsertOne) Update(set func(*ListingUpsert)) *ListingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ListingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ListingUpsertOne) SetUpdateTime(v time.Time) *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ListingUpsertOne) UpdateUpdateTime() *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetPlayerID sets the "player_id" field.
func (u *ListingUpsertOne) SetPlayerID(v string) *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.SetPlayerID(v)
	})
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *ListingUpsertOne) UpdatePlayerID() *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.UpdatePlayerID()
	})
}

// SetCardID sets the "card_id" field.
func (u *ListingUpsertOne) SetCardID(v uuid.UUID) *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.SetCardID(v)
	})
}

// UpdateCardID sets the "card_id" field to the value that was provided on create.
func (u *ListingUpsertOne) UpdateCardID() *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.UpdateCardID()
	})
}

// SetPrice sets the "price" field.
func (u *ListingUpsertOne) SetPrice(v int64) *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ListingUpsertOne) AddPrice(v int64) *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ListingUpsertOne) UpdatePrice() *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.UpdatePrice()
	})
}

// SetNote sets the "note" field.
func (u *ListingUpsertOne) SetNote(v string) *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ListingUpsertOne) UpdateNote() *ListingUpsertOne {
	return u.Update(func(s *ListingUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *ListingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ListingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ListingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ListingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ListingUpsertOne.ID is not supported by MySQL driver. Use ListingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ListingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ListingCreateBulk is the builder for creating many Listing entities in bulk.
type ListingCreateBulk struct {
	config
	err      error
	builders []*ListingCreate
	conflict []sql.ConflictOption
}

// Save creates the Listing entities in the database.
func (lcb *ListingCreateBulk) Save(ctx context.Context) ([]*Listing, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Listing, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = lcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *ListingCreateBulk) SaveX(ctx context.Context) []*Listing {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *ListingCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *ListingCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Listing.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ListingUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (lcb *ListingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ListingUpsertBulk {
	lcb.conflict = opts
	return &ListingUpsertBulk{
		create: lcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Listing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (lcb *ListingCreateBulk) OnConflictColumns(columns ...string) *ListingUpsertBulk {
	lcb.conflict = append(lcb.conflict, sql.ConflictColumns(columns...))
	return &ListingUpsertBulk{
		create: lcb,
	}
}

// ListingUpsertBulk is the builder for "upsert"-ing
// a bulk of Listing nodes.
type ListingUpsertBulk struct {
	create *ListingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Listing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(listing.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ListingUpsertBulk) UpdateNewValues() *ListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(listing.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(listing.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Listing.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ListingUpsertBulk) Ignore() *ListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ListingUpsertBulk) DoNothing() *ListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ListingCreateBulk.OnConflict
// documentation for more info.
func (u *ListingUpsertBulk) Update(set func(*ListingUpsert)) *ListingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ListingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ListingUpsertBulk) SetUpdateTime(v time.Time) *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ListingUpsertBulk) UpdateUpdateTime() *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetPlayerID sets the "player_id" field.
func (u *ListingUpsertBulk) SetPlayerID(v string) *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.SetPlayerID(v)
	})
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *ListingUpsertBulk) UpdatePlayerID() *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.UpdatePlayerID()
	})
}

// SetCardID sets the "card_id" field.
func (u *ListingUpsertBulk) SetCardID(v uuid.UUID) *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.SetCardID(v)
	})
}

// UpdateCardID sets the "card_id" field to the value that was provided on create.
func (u *ListingUpsertBulk) UpdateCardID() *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.UpdateCardID()
	})
}

// SetPrice sets the "price" field.
func (u *ListingUpsertBulk) SetPrice(v int64) *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ListingUpsertBulk) AddPrice(v int64) *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ListingUpsertBulk) UpdatePrice() *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.UpdatePrice()
	})
}

// SetNote sets the "note" field.
func (u *ListingUpsertBulk) SetNote(v string) *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ListingUpsertBulk) UpdateNote() *ListingUpsertBulk {
	return u.Update(func(s *ListingUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *ListingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ListingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ListingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ListingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
