// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/card"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/playerfavoritecards"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
)

// PlayerFavoriteCardsUpdate is the builder for updating PlayerFavoriteCards entities.
type PlayerFavoriteCardsUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerFavoriteCardsMutation
}

// Where appends a list predicates to the PlayerFavoriteCardsUpdate builder.
func (pfcu *PlayerFavoriteCardsUpdate) Where(ps ...predicate.PlayerFavoriteCards) *PlayerFavoriteCardsUpdate {
	pfcu.mutation.Where(ps...)
	return pfcu
}

// SetUpdateTime sets the "update_time" field.
func (pfcu *PlayerFavoriteCardsUpdate) SetUpdateTime(t time.Time) *PlayerFavoriteCardsUpdate {
	pfcu.mutation.SetUpdateTime(t)
	return pfcu
}

// SetPlayerID sets the "player_id" field.
func (pfcu *PlayerFavoriteCardsUpdate) SetPlayerID(s string) *PlayerFavoriteCardsUpdate {
	pfcu.mutation.SetPlayerID(s)
	return pfcu
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (pfcu *PlayerFavoriteCardsUpdate) SetNillablePlayerID(s *string) *PlayerFavoriteCardsUpdate {
	if s != nil {
		pfcu.SetPlayerID(*s)
	}
	return pfcu
}

// SetCardID sets the "card_id" field.
func (pfcu *PlayerFavoriteCardsUpdate) SetCardID(u uuid.UUID) *PlayerFavoriteCardsUpdate {
	pfcu.mutation.SetCardID(u)
	return pfcu
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (pfcu *PlayerFavoriteCardsUpdate) SetNillableCardID(u *uuid.UUID) *PlayerFavoriteCardsUpdate {
	if u != nil {
		pfcu.SetCardID(*u)
	}
	return pfcu
}

// SetPosition sets the "position" field.
func (pfcu *PlayerFavoriteCardsUpdate) SetPosition(f float64) *PlayerFavoriteCardsUpdate {
	pfcu.mutation.ResetPosition()
	pfcu.mutation.SetPosition(f)
	return pfcu
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (pfcu *PlayerFavoriteCardsUpdate) SetNillablePosition(f *float64) *PlayerFavoriteCardsUpdate {
	if f != nil {
		pfcu.SetPosition(*f)
	}
	return pfcu
}

// AddPosition adds f to the "position" field.
func (pfcu *PlayerFavoriteCardsUpdate) AddPosition(f float64) *PlayerFavoriteCardsUpdate {
	pfcu.mutation.AddPosition(f)
	return pfcu
}

// SetPlayer sets the "player" edge to the Player entity.
func (pfcu *PlayerFavoriteCardsUpdate) SetPlayer(p *Player) *PlayerFavoriteCardsUpdate {
	return pfcu.SetPlayerID(p.ID)
}

// SetCard sets the "card" edge to the Card entity.
func (pfcu *PlayerFavoriteCardsUpdate) SetCard(c *Card) *PlayerFavoriteCardsUpdate {
	return pfcu.SetCardID(c.ID)
}

// Mutation returns the PlayerFavoriteCardsMutation object of the builder.
func (pfcu *PlayerFavoriteCardsUpdate) Mutation() *PlayerFavoriteCardsMutation {
	return pfcu.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (pfcu *PlayerFavoriteCardsUpdate) ClearPlayer() *PlayerFavoriteCardsUpdate {
	pfcu.mutation.ClearPlayer()
	return pfcu
}

// ClearCard clears the "card" edge to the Card entity.
func (pfcu *PlayerFavoriteCardsUpdate) ClearCard() *PlayerFavoriteCardsUpdate {
	pfcu.mutation.ClearCard()
	return pfcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pfcu *PlayerFavoriteCardsUpdate) Save(ctx context.Context) (int, error) {
	pfcu.defaults()
	return withHooks(ctx, pfcu.sqlSave, pfcu.mutation, pfcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pfcu *PlayerFavoriteCardsUpdate) SaveX(ctx context.Context) int {
	affected, err := pfcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pfcu *PlayerFavoriteCardsUpdate) Exec(ctx context.Context) error {
	_, err := pfcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfcu *PlayerFavoriteCardsUpdate) ExecX(ctx context.Context) {
	if err := pfcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pfcu *PlayerFavoriteCardsUpdate) defaults() {
	if _, ok := pfcu.mutation.UpdateTime(); !ok {
		v := playerfavoritecards.UpdateDefaultUpdateTime()
		pfcu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pfcu *PlayerFavoriteCardsUpdate) check() error {
	if pfcu.mutation.PlayerCleared() && len(pfcu.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerFavoriteCards.player"`)
	}
	if pfcu.mutation.CardCleared() && len(pfcu.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerFavoriteCards.card"`)
	}
	return nil
}

func (pfcu *PlayerFavoriteCardsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pfcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(playerfavoritecards.Table, playerfavoritecards.Columns, sqlgraph.NewFieldSpec(playerfavoritecards.FieldPlayerID, field.TypeString), sqlgraph.NewFieldSpec(playerfavoritecards.FieldCardID, field.TypeUUID))
	if ps := pfcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pfcu.mutation.UpdateTime(); ok {
		_spec.SetField(playerfavoritecards.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pfcu.mutation.Position(); ok {
		_spec.SetField(playerfavoritecards.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := pfcu.mutation.AddedPosition(); ok {
		_spec.AddField(playerfavoritecards.FieldPosition, field.TypeFloat64, value)
	}
	if pfcu.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.PlayerTable,
			Columns: []string{playerfavoritecards.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pfcu.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.PlayerTable,
			Columns: []string{playerfavoritecards.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pfcu.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.CardTable,
			Columns: []string{playerfavoritecards.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pfcu.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.CardTable,
			Columns: []string{playerfavoritecards.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pfcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerfavoritecards.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pfcu.mutation.done = true
	return n, nil
}

// PlayerFavoriteCardsUpdateOne is the builder for updating a single PlayerFavoriteCards entity.
type PlayerFavoriteCardsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerFavoriteCardsMutation
}

// SetUpdateTime sets the "update_time" field.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetUpdateTime(t time.Time) *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.SetUpdateTime(t)
	return pfcuo
}

// SetPlayerID sets the "player_id" field.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetPlayerID(s string) *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.SetPlayerID(s)
	return pfcuo
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetNillablePlayerID(s *string) *PlayerFavoriteCardsUpdateOne {
	if s != nil {
		pfcuo.SetPlayerID(*s)
	}
	return pfcuo
}

// SetCardID sets the "card_id" field.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetCardID(u uuid.UUID) *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.SetCardID(u)
	return pfcuo
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetNillableCardID(u *uuid.UUID) *PlayerFavoriteCardsUpdateOne {
	if u != nil {
		pfcuo.SetCardID(*u)
	}
	return pfcuo
}

// SetPosition sets the "position" field.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetPosition(f float64) *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.ResetPosition()
	pfcuo.mutation.SetPosition(f)
	return pfcuo
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetNillablePosition(f *float64) *PlayerFavoriteCardsUpdateOne {
	if f != nil {
		pfcuo.SetPosition(*f)
	}
	return pfcuo
}

// AddPosition adds f to the "position" field.
func (pfcuo *PlayerFavoriteCardsUpdateOne) AddPosition(f float64) *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.AddPosition(f)
	return pfcuo
}

// SetPlayer sets the "player" edge to the Player entity.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetPlayer(p *Player) *PlayerFavoriteCardsUpdateOne {
	return pfcuo.SetPlayerID(p.ID)
}

// SetCard sets the "card" edge to the Card entity.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SetCard(c *Card) *PlayerFavoriteCardsUpdateOne {
	return pfcuo.SetCardID(c.ID)
}

// Mutation returns the PlayerFavoriteCardsMutation object of the builder.
func (pfcuo *PlayerFavoriteCardsUpdateOne) Mutation() *PlayerFavoriteCardsMutation {
	return pfcuo.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (pfcuo *PlayerFavoriteCardsUpdateOne) ClearPlayer() *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.ClearPlayer()
	return pfcuo
}

// ClearCard clears the "card" edge to the Card entity.
func (pfcuo *PlayerFavoriteCardsUpdateOne) ClearCard() *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.ClearCard()
	return pfcuo
}

// Where appends a list predicates to the PlayerFavoriteCardsUpdate builder.
func (pfcuo *PlayerFavoriteCardsUpdateOne) Where(ps ...predicate.PlayerFavoriteCards) *PlayerFavoriteCardsUpdateOne {
	pfcuo.mutation.Where(ps...)
	return pfcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pfcuo *PlayerFavoriteCardsUpdateOne) Select(field string, fields ...string) *PlayerFavoriteCardsUpdateOne {
	pfcuo.fields = append([]string{field}, fields...)
	return pfcuo
}

// Save executes the query and returns the updated PlayerFavoriteCards entity.
func (pfcuo *PlayerFavoriteCardsUpdateOne) Save(ctx context.Context) (*PlayerFavoriteCards, error) {
	pfcuo.defaults()
	return withHooks(ctx, pfcuo.sqlSave, pfcuo.mutation, pfcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pfcuo *PlayerFavoriteCardsUpdateOne) SaveX(ctx context.Context) *PlayerFavoriteCards {
	node, err := pfcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pfcuo *PlayerFavoriteCardsUpdateOne) Exec(ctx context.Context) error {
	_, err := pfcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfcuo *PlayerFavoriteCardsUpdateOne) ExecX(ctx context.Context) {
	if err := pfcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pfcuo *PlayerFavoriteCardsUpdateOne) defaults() {
	if _, ok := pfcuo.mutation.UpdateTime(); !ok {
		v := playerfavoritecards.UpdateDefaultUpdateTime()
		pfcuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pfcuo *PlayerFavoriteCardsUpdateOne) check() error {
	if pfcuo.mutation.PlayerCleared() && len(pfcuo.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerFavoriteCards.player"`)
	}
	if pfcuo.mutation.CardCleared() && len(pfcuo.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerFavoriteCards.card"`)
	}
	return nil
}

func (pfcuo *PlayerFavoriteCardsUpdateOne) sqlSave(ctx context.Context) (_node *PlayerFavoriteCards, err error) {
	if err := pfcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playerfavoritecards.Table, playerfavoritecards.Columns, sqlgraph.NewFieldSpec(playerfavoritecards.FieldPlayerID, field.TypeString), sqlgraph.NewFieldSpec(playerfavoritecards.FieldCardID, field.TypeUUID))
	if id, ok := pfcuo.mutation.PlayerID(); !ok {
		return nil, &ValidationError{Name: "player_id", err: errors.New(`ent: missing "PlayerFavoriteCards.player_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := pfcuo.mutation.CardID(); !ok {
		return nil, &ValidationError{Name: "card_id", err: errors.New(`ent: missing "PlayerFavoriteCards.card_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := pfcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !playerfavoritecards.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := pfcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pfcuo.mutation.UpdateTime(); ok {
		_spec.SetField(playerfavoritecards.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pfcuo.mutation.Position(); ok {
		_spec.SetField(playerfavoritecards.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := pfcuo.mutation.AddedPosition(); ok {
		_spec.AddField(playerfavoritecards.FieldPosition, field.TypeFloat64, value)
	}
	if pfcuo.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.PlayerTable,
			Columns: []string{playerfavoritecards.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pfcuo.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.PlayerTable,
			Columns: []string{playerfavoritecards.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pfcuo.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.CardTable,
			Columns: []string{playerfavoritecards.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pfcuo.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   playerfavoritecards.CardTable,
			Columns: []string{playerfavoritecards.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlayerFavoriteCards{config: pfcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pfcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerfavoritecards.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pfcuo.mutation.done = true
	return _node, nil
}
