// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/rwbyadv3/ent/playerlimit"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
)

// PlayerLimitDelete is the builder for deleting a PlayerLimit entity.
type PlayerLimitDelete struct {
	config
	hooks    []Hook
	mutation *PlayerLimitMutation
}

// Where appends a list predicates to the PlayerLimitDelete builder.
func (pld *PlayerLimitDelete) Where(ps ...predicate.PlayerLimit) *PlayerLimitDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *PlayerLimitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pld.sqlExec, pld.mutation, pld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *PlayerLimitDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *PlayerLimitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(playerlimit.Table, sqlgraph.NewFieldSpec(playerlimit.FieldID, field.TypeInt))
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pld.mutation.done = true
	return affected, err
}

// PlayerLimitDeleteOne is the builder for deleting a single PlayerLimit entity.
type PlayerLimitDeleteOne struct {
	pld *PlayerLimitDelete
}

// Where appends a list predicates to the PlayerLimitDelete builder.
func (pldo *PlayerLimitDeleteOne) Where(ps ...predicate.PlayerLimit) *PlayerLimitDeleteOne {
	pldo.pld.mutation.Where(ps...)
	return pldo
}

// Exec executes the deletion query.
func (pldo *PlayerLimitDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{playerlimit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *PlayerLimitDeleteOne) ExecX(ctx context.Context) {
	if err := pldo.Exec(ctx); err != nil {
		panic(err)
	}
}
