// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yyewolf/rwbyadv3/ent/card"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/playerfavoritecards"
)

// PlayerFavoriteCards is the model entity for the PlayerFavoriteCards schema.
type PlayerFavoriteCards struct {
	config `json:"-"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty,omitzero"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty,omitzero"`
	// PlayerID holds the value of the "player_id" field.
	PlayerID string `json:"player_id,omitempty,omitzero"`
	// CardID holds the value of the "card_id" field.
	CardID uuid.UUID `json:"card_id,omitempty,omitzero"`
	// Position holds the value of the "position" field.
	Position float64 `json:"position,omitempty,omitzero"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayerFavoriteCardsQuery when eager-loading is set.
	Edges        PlayerFavoriteCardsEdges `json:"edges,omitempty"`
	selectValues sql.SelectValues
}

// PlayerFavoriteCardsEdges holds the relations/edges for other nodes in the graph.
type PlayerFavoriteCardsEdges struct {
	// Player holds the value of the player edge.
	Player *Player `json:"player,omitempty,omitzero"`
	// Card holds the value of the card edge.
	Card *Card `json:"card,omitempty,omitzero"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerFavoriteCardsEdges) PlayerOrErr() (*Player, error) {
	if e.Player != nil {
		return e.Player, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "player"}
}

// CardOrErr returns the Card value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerFavoriteCardsEdges) CardOrErr() (*Card, error) {
	if e.Card != nil {
		return e.Card, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: card.Label}
	}
	return nil, &NotLoadedError{edge: "card"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerFavoriteCards) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playerfavoritecards.FieldPosition:
			values[i] = new(sql.NullFloat64)
		case playerfavoritecards.FieldPlayerID:
			values[i] = new(sql.NullString)
		case playerfavoritecards.FieldCreateTime, playerfavoritecards.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case playerfavoritecards.FieldCardID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerFavoriteCards fields.
func (pfc *PlayerFavoriteCards) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playerfavoritecards.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				pfc.CreateTime = value.Time
			}
		case playerfavoritecards.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				pfc.UpdateTime = value.Time
			}
		case playerfavoritecards.FieldPlayerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field player_id", values[i])
			} else if value.Valid {
				pfc.PlayerID = value.String
			}
		case playerfavoritecards.FieldCardID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field card_id", values[i])
			} else if value != nil {
				pfc.CardID = *value
			}
		case playerfavoritecards.FieldPosition:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				pfc.Position = value.Float64
			}
		default:
			pfc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerFavoriteCards.
// This includes values selected through modifiers, order, etc.
func (pfc *PlayerFavoriteCards) Value(name string) (ent.Value, error) {
	return pfc.selectValues.Get(name)
}

// QueryPlayer queries the "player" edge of the PlayerFavoriteCards entity.
func (pfc *PlayerFavoriteCards) QueryPlayer() *PlayerQuery {
	return NewPlayerFavoriteCardsClient(pfc.config).QueryPlayer(pfc)
}

// QueryCard queries the "card" edge of the PlayerFavoriteCards entity.
func (pfc *PlayerFavoriteCards) QueryCard() *CardQuery {
	return NewPlayerFavoriteCardsClient(pfc.config).QueryCard(pfc)
}

// Update returns a builder for updating this PlayerFavoriteCards.
// Note that you need to call PlayerFavoriteCards.Unwrap() before calling this method if this PlayerFavoriteCards
// was returned from a transaction, and the transaction was committed or rolled back.
func (pfc *PlayerFavoriteCards) Update() *PlayerFavoriteCardsUpdateOne {
	return NewPlayerFavoriteCardsClient(pfc.config).UpdateOne(pfc)
}

// Unwrap unwraps the PlayerFavoriteCards entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pfc *PlayerFavoriteCards) Unwrap() *PlayerFavoriteCards {
	_tx, ok := pfc.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerFavoriteCards is not a transactional entity")
	}
	pfc.config.driver = _tx.drv
	return pfc
}

// String implements the fmt.Stringer.
func (pfc *PlayerFavoriteCards) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerFavoriteCards(")
	builder.WriteString("create_time=")
	builder.WriteString(pfc.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(pfc.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("player_id=")
	builder.WriteString(pfc.PlayerID)
	builder.WriteString(", ")
	builder.WriteString("card_id=")
	builder.WriteString(fmt.Sprintf("%v", pfc.CardID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", pfc.Position))
	builder.WriteByte(')')
	return builder.String()
}

// PlayerFavoriteCardsSlice is a parsable slice of PlayerFavoriteCards.
type PlayerFavoriteCardsSlice []*PlayerFavoriteCards
