// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/yyewolf/rwbyadv3/ent/player"
	"github.com/yyewolf/rwbyadv3/ent/predicate"
	"github.com/yyewolf/rwbyadv3/ent/trade"
)

// TradeUpdate is the builder for updating Trade entities.
type TradeUpdate struct {
	config
	hooks    []Hook
	mutation *TradeMutation
}

// Where appends a list predicates to the TradeUpdate builder.
func (tu *TradeUpdate) Where(ps ...predicate.Trade) *TradeUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUpdateTime sets the "update_time" field.
func (tu *TradeUpdate) SetUpdateTime(t time.Time) *TradeUpdate {
	tu.mutation.SetUpdateTime(t)
	return tu
}

// SetInitiatorID sets the "initiator_id" field.
func (tu *TradeUpdate) SetInitiatorID(s string) *TradeUpdate {
	tu.mutation.SetInitiatorID(s)
	return tu
}

// SetNillableInitiatorID sets the "initiator_id" field if the given value is not nil.
func (tu *TradeUpdate) SetNillableInitiatorID(s *string) *TradeUpdate {
	if s != nil {
		tu.SetInitiatorID(*s)
	}
	return tu
}

// SetReceiverID sets the "receiver_id" field.
func (tu *TradeUpdate) SetReceiverID(s string) *TradeUpdate {
	tu.mutation.SetReceiverID(s)
	return tu
}

// SetNillableReceiverID sets the "receiver_id" field if the given value is not nil.
func (tu *TradeUpdate) SetNillableReceiverID(s *string) *TradeUpdate {
	if s != nil {
		tu.SetReceiverID(*s)
	}
	return tu
}

// SetLiens sets the "liens" field.
func (tu *TradeUpdate) SetLiens(i int) *TradeUpdate {
	tu.mutation.ResetLiens()
	tu.mutation.SetLiens(i)
	return tu
}

// SetNillableLiens sets the "liens" field if the given value is not nil.
func (tu *TradeUpdate) SetNillableLiens(i *int) *TradeUpdate {
	if i != nil {
		tu.SetLiens(*i)
	}
	return tu
}

// AddLiens adds i to the "liens" field.
func (tu *TradeUpdate) AddLiens(i int) *TradeUpdate {
	tu.mutation.AddLiens(i)
	return tu
}

// SetOfferCards sets the "offer_cards" field.
func (tu *TradeUpdate) SetOfferCards(s []string) *TradeUpdate {
	tu.mutation.SetOfferCards(s)
	return tu
}

// AppendOfferCards appends s to the "offer_cards" field.
func (tu *TradeUpdate) AppendOfferCards(s []string) *TradeUpdate {
	tu.mutation.AppendOfferCards(s)
	return tu
}

// SetReceiveCards sets the "receive_cards" field.
func (tu *TradeUpdate) SetReceiveCards(s []string) *TradeUpdate {
	tu.mutation.SetReceiveCards(s)
	return tu
}

// AppendReceiveCards appends s to the "receive_cards" field.
func (tu *TradeUpdate) AppendReceiveCards(s []string) *TradeUpdate {
	tu.mutation.AppendReceiveCards(s)
	return tu
}

// SetInitiator sets the "initiator" edge to the Player entity.
func (tu *TradeUpdate) SetInitiator(p *Player) *TradeUpdate {
	return tu.SetInitiatorID(p.ID)
}

// SetReceiver sets the "receiver" edge to the Player entity.
func (tu *TradeUpdate) SetReceiver(p *Player) *TradeUpdate {
	return tu.SetReceiverID(p.ID)
}

// Mutation returns the TradeMutation object of the builder.
func (tu *TradeUpdate) Mutation() *TradeMutation {
	return tu.mutation
}

// ClearInitiator clears the "initiator" edge to the Player entity.
func (tu *TradeUpdate) ClearInitiator() *TradeUpdate {
	tu.mutation.ClearInitiator()
	return tu
}

// ClearReceiver clears the "receiver" edge to the Player entity.
func (tu *TradeUpdate) ClearReceiver() *TradeUpdate {
	tu.mutation.ClearReceiver()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TradeUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TradeUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TradeUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TradeUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TradeUpdate) defaults() {
	if _, ok := tu.mutation.UpdateTime(); !ok {
		v := trade.UpdateDefaultUpdateTime()
		tu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TradeUpdate) check() error {
	if tu.mutation.InitiatorCleared() && len(tu.mutation.InitiatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Trade.initiator"`)
	}
	if tu.mutation.ReceiverCleared() && len(tu.mutation.ReceiverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Trade.receiver"`)
	}
	return nil
}

func (tu *TradeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(trade.Table, trade.Columns, sqlgraph.NewFieldSpec(trade.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UpdateTime(); ok {
		_spec.SetField(trade.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Liens(); ok {
		_spec.SetField(trade.FieldLiens, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedLiens(); ok {
		_spec.AddField(trade.FieldLiens, field.TypeInt, value)
	}
	if value, ok := tu.mutation.OfferCards(); ok {
		_spec.SetField(trade.FieldOfferCards, field.TypeJSON, value)
	}
	if value, ok := tu.mutation.AppendedOfferCards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, trade.FieldOfferCards, value)
		})
	}
	if value, ok := tu.mutation.ReceiveCards(); ok {
		_spec.SetField(trade.FieldReceiveCards, field.TypeJSON, value)
	}
	if value, ok := tu.mutation.AppendedReceiveCards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, trade.FieldReceiveCards, value)
		})
	}
	if tu.mutation.InitiatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.InitiatorTable,
			Columns: []string{trade.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.InitiatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.InitiatorTable,
			Columns: []string{trade.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.ReceiverTable,
			Columns: []string{trade.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.ReceiverTable,
			Columns: []string{trade.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trade.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TradeUpdateOne is the builder for updating a single Trade entity.
type TradeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TradeMutation
}

// SetUpdateTime sets the "update_time" field.
func (tuo *TradeUpdateOne) SetUpdateTime(t time.Time) *TradeUpdateOne {
	tuo.mutation.SetUpdateTime(t)
	return tuo
}

// SetInitiatorID sets the "initiator_id" field.
func (tuo *TradeUpdateOne) SetInitiatorID(s string) *TradeUpdateOne {
	tuo.mutation.SetInitiatorID(s)
	return tuo
}

// SetNillableInitiatorID sets the "initiator_id" field if the given value is not nil.
func (tuo *TradeUpdateOne) SetNillableInitiatorID(s *string) *TradeUpdateOne {
	if s != nil {
		tuo.SetInitiatorID(*s)
	}
	return tuo
}

// SetReceiverID sets the "receiver_id" field.
func (tuo *TradeUpdateOne) SetReceiverID(s string) *TradeUpdateOne {
	tuo.mutation.SetReceiverID(s)
	return tuo
}

// SetNillableReceiverID sets the "receiver_id" field if the given value is not nil.
func (tuo *TradeUpdateOne) SetNillableReceiverID(s *string) *TradeUpdateOne {
	if s != nil {
		tuo.SetReceiverID(*s)
	}
	return tuo
}

// SetLiens sets the "liens" field.
func (tuo *TradeUpdateOne) SetLiens(i int) *TradeUpdateOne {
	tuo.mutation.ResetLiens()
	tuo.mutation.SetLiens(i)
	return tuo
}

// SetNillableLiens sets the "liens" field if the given value is not nil.
func (tuo *TradeUpdateOne) SetNillableLiens(i *int) *TradeUpdateOne {
	if i != nil {
		tuo.SetLiens(*i)
	}
	return tuo
}

// AddLiens adds i to the "liens" field.
func (tuo *TradeUpdateOne) AddLiens(i int) *TradeUpdateOne {
	tuo.mutation.AddLiens(i)
	return tuo
}

// SetOfferCards sets the "offer_cards" field.
func (tuo *TradeUpdateOne) SetOfferCards(s []string) *TradeUpdateOne {
	tuo.mutation.SetOfferCards(s)
	return tuo
}

// AppendOfferCards appends s to the "offer_cards" field.
func (tuo *TradeUpdateOne) AppendOfferCards(s []string) *TradeUpdateOne {
	tuo.mutation.AppendOfferCards(s)
	return tuo
}

// SetReceiveCards sets the "receive_cards" field.
func (tuo *TradeUpdateOne) SetReceiveCards(s []string) *TradeUpdateOne {
	tuo.mutation.SetReceiveCards(s)
	return tuo
}

// AppendReceiveCards appends s to the "receive_cards" field.
func (tuo *TradeUpdateOne) AppendReceiveCards(s []string) *TradeUpdateOne {
	tuo.mutation.AppendReceiveCards(s)
	return tuo
}

// SetInitiator sets the "initiator" edge to the Player entity.
func (tuo *TradeUpdateOne) SetInitiator(p *Player) *TradeUpdateOne {
	return tuo.SetInitiatorID(p.ID)
}

// SetReceiver sets the "receiver" edge to the Player entity.
func (tuo *TradeUpdateOne) SetReceiver(p *Player) *TradeUpdateOne {
	return tuo.SetReceiverID(p.ID)
}

// Mutation returns the TradeMutation object of the builder.
func (tuo *TradeUpdateOne) Mutation() *TradeMutation {
	return tuo.mutation
}

// ClearInitiator clears the "initiator" edge to the Player entity.
func (tuo *TradeUpdateOne) ClearInitiator() *TradeUpdateOne {
	tuo.mutation.ClearInitiator()
	return tuo
}

// ClearReceiver clears the "receiver" edge to the Player entity.
func (tuo *TradeUpdateOne) ClearReceiver() *TradeUpdateOne {
	tuo.mutation.ClearReceiver()
	return tuo
}

// Where appends a list predicates to the TradeUpdate builder.
func (tuo *TradeUpdateOne) Where(ps ...predicate.Trade) *TradeUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TradeUpdateOne) Select(field string, fields ...string) *TradeUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Trade entity.
func (tuo *TradeUpdateOne) Save(ctx context.Context) (*Trade, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TradeUpdateOne) SaveX(ctx context.Context) *Trade {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TradeUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TradeUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TradeUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdateTime(); !ok {
		v := trade.UpdateDefaultUpdateTime()
		tuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TradeUpdateOne) check() error {
	if tuo.mutation.InitiatorCleared() && len(tuo.mutation.InitiatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Trade.initiator"`)
	}
	if tuo.mutation.ReceiverCleared() && len(tuo.mutation.ReceiverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Trade.receiver"`)
	}
	return nil
}

func (tuo *TradeUpdateOne) sqlSave(ctx context.Context) (_node *Trade, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trade.Table, trade.Columns, sqlgraph.NewFieldSpec(trade.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Trade.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trade.FieldID)
		for _, f := range fields {
			if !trade.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trade.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UpdateTime(); ok {
		_spec.SetField(trade.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Liens(); ok {
		_spec.SetField(trade.FieldLiens, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedLiens(); ok {
		_spec.AddField(trade.FieldLiens, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.OfferCards(); ok {
		_spec.SetField(trade.FieldOfferCards, field.TypeJSON, value)
	}
	if value, ok := tuo.mutation.AppendedOfferCards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, trade.FieldOfferCards, value)
		})
	}
	if value, ok := tuo.mutation.ReceiveCards(); ok {
		_spec.SetField(trade.FieldReceiveCards, field.TypeJSON, value)
	}
	if value, ok := tuo.mutation.AppendedReceiveCards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, trade.FieldReceiveCards, value)
		})
	}
	if tuo.mutation.InitiatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.InitiatorTable,
			Columns: []string{trade.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.InitiatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.InitiatorTable,
			Columns: []string{trade.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.ReceiverTable,
			Columns: []string{trade.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   trade.ReceiverTable,
			Columns: []string{trade.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Trade{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trade.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
