// Code generated by ent, DO NOT EDIT.

package player

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the player type in the database.
	Label = "player"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldLiens holds the string denoting the liens field in the database.
	FieldLiens = "liens"
	// FieldLiensInAuction holds the string denoting the liens_in_auction field in the database.
	FieldLiensInAuction = "liens_in_auction"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldExperiencePoints holds the string denoting the experience_points field in the database.
	FieldExperiencePoints = "experience_points"
	// FieldExperiencePointsThreshold holds the string denoting the experience_points_threshold field in the database.
	FieldExperiencePointsThreshold = "experience_points_threshold"
	// FieldBackpackLevel holds the string denoting the backpack_level field in the database.
	FieldBackpackLevel = "backpack_level"
	// FieldBackpackReservedSlots holds the string denoting the backpack_reserved_slots field in the database.
	FieldBackpackReservedSlots = "backpack_reserved_slots"
	// FieldSelectedCardID holds the string denoting the selected_card_id field in the database.
	FieldSelectedCardID = "selected_card_id"
	// EdgeLimits holds the string denoting the limits edge name in mutations.
	EdgeLimits = "limits"
	// EdgeCards holds the string denoting the cards edge name in mutations.
	EdgeCards = "cards"
	// EdgeFavoriteCards holds the string denoting the favorite_cards edge name in mutations.
	EdgeFavoriteCards = "favorite_cards"
	// EdgeDeck holds the string denoting the deck edge name in mutations.
	EdgeDeck = "deck"
	// EdgeLootboxes holds the string denoting the lootboxes edge name in mutations.
	EdgeLootboxes = "lootboxes"
	// EdgeSelectedCard holds the string denoting the selected_card edge name in mutations.
	EdgeSelectedCard = "selected_card"
	// EdgeGithubStar holds the string denoting the github_star edge name in mutations.
	EdgeGithubStar = "github_star"
	// EdgeDaily holds the string denoting the daily edge name in mutations.
	EdgeDaily = "daily"
	// EdgeAuctions holds the string denoting the auctions edge name in mutations.
	EdgeAuctions = "auctions"
	// EdgeListings holds the string denoting the listings edge name in mutations.
	EdgeListings = "listings"
	// EdgeDungeons holds the string denoting the dungeons edge name in mutations.
	EdgeDungeons = "dungeons"
	// EdgeTrades holds the string denoting the trades edge name in mutations.
	EdgeTrades = "trades"
	// EdgeTradesReceived holds the string denoting the trades_received edge name in mutations.
	EdgeTradesReceived = "trades_received"
	// EdgePlayerFavoriteCards holds the string denoting the player_favorite_cards edge name in mutations.
	EdgePlayerFavoriteCards = "player_favorite_cards"
	// EdgePlayerDecks holds the string denoting the player_decks edge name in mutations.
	EdgePlayerDecks = "player_decks"
	// Table holds the table name of the player in the database.
	Table = "players"
	// LimitsTable is the table that holds the limits relation/edge.
	LimitsTable = "player_limits"
	// LimitsInverseTable is the table name for the PlayerLimit entity.
	// It exists in this package in order to avoid circular dependency with the "playerlimit" package.
	LimitsInverseTable = "player_limits"
	// LimitsColumn is the table column denoting the limits relation/edge.
	LimitsColumn = "player_id"
	// CardsTable is the table that holds the cards relation/edge.
	CardsTable = "cards"
	// CardsInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	CardsInverseTable = "cards"
	// CardsColumn is the table column denoting the cards relation/edge.
	CardsColumn = "player_id"
	// FavoriteCardsTable is the table that holds the favorite_cards relation/edge. The primary key declared below.
	FavoriteCardsTable = "player_favorite_cards"
	// FavoriteCardsInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	FavoriteCardsInverseTable = "cards"
	// DeckTable is the table that holds the deck relation/edge. The primary key declared below.
	DeckTable = "player_decks"
	// DeckInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	DeckInverseTable = "cards"
	// LootboxesTable is the table that holds the lootboxes relation/edge.
	LootboxesTable = "loot_boxes"
	// LootboxesInverseTable is the table name for the LootBox entity.
	// It exists in this package in order to avoid circular dependency with the "lootbox" package.
	LootboxesInverseTable = "loot_boxes"
	// LootboxesColumn is the table column denoting the lootboxes relation/edge.
	LootboxesColumn = "player_id"
	// SelectedCardTable is the table that holds the selected_card relation/edge.
	SelectedCardTable = "players"
	// SelectedCardInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	SelectedCardInverseTable = "cards"
	// SelectedCardColumn is the table column denoting the selected_card relation/edge.
	SelectedCardColumn = "selected_card_id"
	// GithubStarTable is the table that holds the github_star relation/edge.
	GithubStarTable = "github_stars"
	// GithubStarInverseTable is the table name for the GithubStar entity.
	// It exists in this package in order to avoid circular dependency with the "githubstar" package.
	GithubStarInverseTable = "github_stars"
	// GithubStarColumn is the table column denoting the github_star relation/edge.
	GithubStarColumn = "player_id"
	// DailyTable is the table that holds the daily relation/edge.
	DailyTable = "dailies"
	// DailyInverseTable is the table name for the Daily entity.
	// It exists in this package in order to avoid circular dependency with the "daily" package.
	DailyInverseTable = "dailies"
	// DailyColumn is the table column denoting the daily relation/edge.
	DailyColumn = "player_id"
	// AuctionsTable is the table that holds the auctions relation/edge.
	AuctionsTable = "auctions"
	// AuctionsInverseTable is the table name for the Auction entity.
	// It exists in this package in order to avoid circular dependency with the "auction" package.
	AuctionsInverseTable = "auctions"
	// AuctionsColumn is the table column denoting the auctions relation/edge.
	AuctionsColumn = "player_id"
	// ListingsTable is the table that holds the listings relation/edge.
	ListingsTable = "listings"
	// ListingsInverseTable is the table name for the Listing entity.
	// It exists in this package in order to avoid circular dependency with the "listing" package.
	ListingsInverseTable = "listings"
	// ListingsColumn is the table column denoting the listings relation/edge.
	ListingsColumn = "player_id"
	// DungeonsTable is the table that holds the dungeons relation/edge.
	DungeonsTable = "dungeons"
	// DungeonsInverseTable is the table name for the Dungeon entity.
	// It exists in this package in order to avoid circular dependency with the "dungeon" package.
	DungeonsInverseTable = "dungeons"
	// DungeonsColumn is the table column denoting the dungeons relation/edge.
	DungeonsColumn = "player_id"
	// TradesTable is the table that holds the trades relation/edge.
	TradesTable = "trades"
	// TradesInverseTable is the table name for the Trade entity.
	// It exists in this package in order to avoid circular dependency with the "trade" package.
	TradesInverseTable = "trades"
	// TradesColumn is the table column denoting the trades relation/edge.
	TradesColumn = "initiator_id"
	// TradesReceivedTable is the table that holds the trades_received relation/edge.
	TradesReceivedTable = "trades"
	// TradesReceivedInverseTable is the table name for the Trade entity.
	// It exists in this package in order to avoid circular dependency with the "trade" package.
	TradesReceivedInverseTable = "trades"
	// TradesReceivedColumn is the table column denoting the trades_received relation/edge.
	TradesReceivedColumn = "receiver_id"
	// PlayerFavoriteCardsTable is the table that holds the player_favorite_cards relation/edge.
	PlayerFavoriteCardsTable = "player_favorite_cards"
	// PlayerFavoriteCardsInverseTable is the table name for the PlayerFavoriteCards entity.
	// It exists in this package in order to avoid circular dependency with the "playerfavoritecards" package.
	PlayerFavoriteCardsInverseTable = "player_favorite_cards"
	// PlayerFavoriteCardsColumn is the table column denoting the player_favorite_cards relation/edge.
	PlayerFavoriteCardsColumn = "player_id"
	// PlayerDecksTable is the table that holds the player_decks relation/edge.
	PlayerDecksTable = "player_decks"
	// PlayerDecksInverseTable is the table name for the PlayerDeck entity.
	// It exists in this package in order to avoid circular dependency with the "playerdeck" package.
	PlayerDecksInverseTable = "player_decks"
	// PlayerDecksColumn is the table column denoting the player_decks relation/edge.
	PlayerDecksColumn = "player_id"
)

// Columns holds all SQL columns for player fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUsername,
	FieldLiens,
	FieldLiensInAuction,
	FieldLevel,
	FieldExperiencePoints,
	FieldExperiencePointsThreshold,
	FieldBackpackLevel,
	FieldBackpackReservedSlots,
	FieldSelectedCardID,
}

var (
	// FavoriteCardsPrimaryKey and FavoriteCardsColumn2 are the table columns denoting the
	// primary key for the favorite_cards relation (M2M).
	FavoriteCardsPrimaryKey = []string{"player_id", "card_id"}
	// DeckPrimaryKey and DeckColumn2 are the table columns denoting the
	// primary key for the deck relation (M2M).
	DeckPrimaryKey = []string{"player_id", "card_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultLiens holds the default value on creation for the "liens" field.
	DefaultLiens int64
	// LiensValidator is a validator for the "liens" field. It is called by the builders before save.
	LiensValidator func(int64) error
	// DefaultLiensInAuction holds the default value on creation for the "liens_in_auction" field.
	DefaultLiensInAuction int64
	// LiensInAuctionValidator is a validator for the "liens_in_auction" field. It is called by the builders before save.
	LiensInAuctionValidator func(int64) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int64
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(int64) error
	// DefaultExperiencePoints holds the default value on creation for the "experience_points" field.
	DefaultExperiencePoints int64
	// ExperiencePointsValidator is a validator for the "experience_points" field. It is called by the builders before save.
	ExperiencePointsValidator func(int64) error
	// DefaultExperiencePointsThreshold holds the default value on creation for the "experience_points_threshold" field.
	DefaultExperiencePointsThreshold int64
	// ExperiencePointsThresholdValidator is a validator for the "experience_points_threshold" field. It is called by the builders before save.
	ExperiencePointsThresholdValidator func(int64) error
	// DefaultBackpackLevel holds the default value on creation for the "backpack_level" field.
	DefaultBackpackLevel int64
	// BackpackLevelValidator is a validator for the "backpack_level" field. It is called by the builders before save.
	BackpackLevelValidator func(int64) error
	// DefaultBackpackReservedSlots holds the default value on creation for the "backpack_reserved_slots" field.
	DefaultBackpackReservedSlots int64
	// BackpackReservedSlotsValidator is a validator for the "backpack_reserved_slots" field. It is called by the builders before save.
	BackpackReservedSlotsValidator func(int64) error
)

// OrderOption defines the ordering options for the Player queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByLiens orders the results by the liens field.
func ByLiens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiens, opts...).ToFunc()
}

// ByLiensInAuction orders the results by the liens_in_auction field.
func ByLiensInAuction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiensInAuction, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByExperiencePoints orders the results by the experience_points field.
func ByExperiencePoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExperiencePoints, opts...).ToFunc()
}

// ByExperiencePointsThreshold orders the results by the experience_points_threshold field.
func ByExperiencePointsThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExperiencePointsThreshold, opts...).ToFunc()
}

// ByBackpackLevel orders the results by the backpack_level field.
func ByBackpackLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackpackLevel, opts...).ToFunc()
}

// ByBackpackReservedSlots orders the results by the backpack_reserved_slots field.
func ByBackpackReservedSlots(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackpackReservedSlots, opts...).ToFunc()
}

// BySelectedCardID orders the results by the selected_card_id field.
func BySelectedCardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectedCardID, opts...).ToFunc()
}

// ByLimitsField orders the results by limits field.
func ByLimitsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLimitsStep(), sql.OrderByField(field, opts...))
	}
}

// ByCardsCount orders the results by cards count.
func ByCardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCardsStep(), opts...)
	}
}

// ByCards orders the results by cards terms.
func ByCards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFavoriteCardsCount orders the results by favorite_cards count.
func ByFavoriteCardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFavoriteCardsStep(), opts...)
	}
}

// ByFavoriteCards orders the results by favorite_cards terms.
func ByFavoriteCards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFavoriteCardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDeckCount orders the results by deck count.
func ByDeckCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeckStep(), opts...)
	}
}

// ByDeck orders the results by deck terms.
func ByDeck(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeckStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLootboxesCount orders the results by lootboxes count.
func ByLootboxesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLootboxesStep(), opts...)
	}
}

// ByLootboxes orders the results by lootboxes terms.
func ByLootboxes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLootboxesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySelectedCardField orders the results by selected_card field.
func BySelectedCardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSelectedCardStep(), sql.OrderByField(field, opts...))
	}
}

// ByGithubStarField orders the results by github_star field.
func ByGithubStarField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGithubStarStep(), sql.OrderByField(field, opts...))
	}
}

// ByDailyField orders the results by daily field.
func ByDailyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDailyStep(), sql.OrderByField(field, opts...))
	}
}

// ByAuctionsCount orders the results by auctions count.
func ByAuctionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuctionsStep(), opts...)
	}
}

// ByAuctions orders the results by auctions terms.
func ByAuctions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuctionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByListingsCount orders the results by listings count.
func ByListingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newListingsStep(), opts...)
	}
}

// ByListings orders the results by listings terms.
func ByListings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDungeonsCount orders the results by dungeons count.
func ByDungeonsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDungeonsStep(), opts...)
	}
}

// ByDungeons orders the results by dungeons terms.
func ByDungeons(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDungeonsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTradesCount orders the results by trades count.
func ByTradesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTradesStep(), opts...)
	}
}

// ByTrades orders the results by trades terms.
func ByTrades(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTradesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTradesReceivedCount orders the results by trades_received count.
func ByTradesReceivedCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTradesReceivedStep(), opts...)
	}
}

// ByTradesReceived orders the results by trades_received terms.
func ByTradesReceived(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTradesReceivedStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPlayerFavoriteCardsCount orders the results by player_favorite_cards count.
func ByPlayerFavoriteCardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlayerFavoriteCardsStep(), opts...)
	}
}

// ByPlayerFavoriteCards orders the results by player_favorite_cards terms.
func ByPlayerFavoriteCards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayerFavoriteCardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPlayerDecksCount orders the results by player_decks count.
func ByPlayerDecksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlayerDecksStep(), opts...)
	}
}

// ByPlayerDecks orders the results by player_decks terms.
func ByPlayerDecks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayerDecksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLimitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LimitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, LimitsTable, LimitsColumn),
	)
}
func newCardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CardsTable, CardsColumn),
	)
}
func newFavoriteCardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FavoriteCardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, FavoriteCardsTable, FavoriteCardsPrimaryKey...),
	)
}
func newDeckStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeckInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DeckTable, DeckPrimaryKey...),
	)
}
func newLootboxesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LootboxesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LootboxesTable, LootboxesColumn),
	)
}
func newSelectedCardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SelectedCardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SelectedCardTable, SelectedCardColumn),
	)
}
func newGithubStarStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GithubStarInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, GithubStarTable, GithubStarColumn),
	)
}
func newDailyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DailyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, DailyTable, DailyColumn),
	)
}
func newAuctionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuctionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuctionsTable, AuctionsColumn),
	)
}
func newListingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ListingsTable, ListingsColumn),
	)
}
func newDungeonsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DungeonsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DungeonsTable, DungeonsColumn),
	)
}
func newTradesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TradesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TradesTable, TradesColumn),
	)
}
func newTradesReceivedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TradesReceivedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TradesReceivedTable, TradesReceivedColumn),
	)
}
func newPlayerFavoriteCardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayerFavoriteCardsInverseTable, PlayerFavoriteCardsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, PlayerFavoriteCardsTable, PlayerFavoriteCardsColumn),
	)
}
func newPlayerDecksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayerDecksInverseTable, PlayerDecksColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, PlayerDecksTable, PlayerDecksColumn),
	)
}
