// Code generated by ent, DO NOT EDIT.

package auction

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the auction type in the database.
	Label = "auction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlayerID holds the string denoting the player_id field in the database.
	FieldPlayerID = "player_id"
	// FieldCardID holds the string denoting the card_id field in the database.
	FieldCardID = "card_id"
	// FieldTimeExtensions holds the string denoting the time_extensions field in the database.
	FieldTimeExtensions = "time_extensions"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// EdgePlayer holds the string denoting the player edge name in mutations.
	EdgePlayer = "player"
	// EdgeBids holds the string denoting the bids edge name in mutations.
	EdgeBids = "bids"
	// Table holds the table name of the auction in the database.
	Table = "auctions"
	// PlayerTable is the table that holds the player relation/edge.
	PlayerTable = "auctions"
	// PlayerInverseTable is the table name for the Player entity.
	// It exists in this package in order to avoid circular dependency with the "player" package.
	PlayerInverseTable = "players"
	// PlayerColumn is the table column denoting the player relation/edge.
	PlayerColumn = "player_id"
	// BidsTable is the table that holds the bids relation/edge.
	BidsTable = "auction_bids"
	// BidsInverseTable is the table name for the AuctionBid entity.
	// It exists in this package in order to avoid circular dependency with the "auctionbid" package.
	BidsInverseTable = "auction_bids"
	// BidsColumn is the table column denoting the bids relation/edge.
	BidsColumn = "auction_id"
)

// Columns holds all SQL columns for auction fields.
var Columns = []string{
	FieldID,
	FieldPlayerID,
	FieldCardID,
	FieldTimeExtensions,
	FieldEndsAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimeExtensions holds the default value on creation for the "time_extensions" field.
	DefaultTimeExtensions int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Auction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlayerID orders the results by the player_id field.
func ByPlayerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerID, opts...).ToFunc()
}

// ByCardID orders the results by the card_id field.
func ByCardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardID, opts...).ToFunc()
}

// ByTimeExtensions orders the results by the time_extensions field.
func ByTimeExtensions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeExtensions, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByPlayerField orders the results by player field.
func ByPlayerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayerStep(), sql.OrderByField(field, opts...))
	}
}

// ByBidsCount orders the results by bids count.
func ByBidsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBidsStep(), opts...)
	}
}

// ByBids orders the results by bids terms.
func ByBids(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBidsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlayerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PlayerTable, PlayerColumn),
	)
}
func newBidsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BidsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BidsTable, BidsColumn),
	)
}
