-- Create "auction_bids" table
CREATE TABLE "auction_bids" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "price" bigint NOT NULL, "auction_id" uuid NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "auctions" table
CREATE TABLE "auctions" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "time_extensions" bigint NOT NULL DEFAULT 0, "ends_at" timestamptz NOT NULL, "card_id" uuid NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "auth_states" table
CREATE TABLE "auth_states" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "redirect_uri" character varying NULL, "expires_at" timestamptz NOT NULL, "type" character varying NOT NULL, "player_id" character varying NULL, PRIMARY KEY ("id"));
-- Create "card_stats" table
CREATE TABLE "card_stats" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "health" bigint NOT NULL, "armor" bigint NOT NULL, "damage" bigint NOT NULL, "healing" bigint NOT NULL, "speed" bigint NOT NULL, "card_id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create index "card_stats_card_id_key" to table: "card_stats"
CREATE UNIQUE INDEX "card_stats_card_id_key" ON "card_stats" ("card_id");
-- Create "card_types" table
CREATE TABLE "card_types" ("id" character varying NOT NULL, "name" character varying NOT NULL, "categories" jsonb NOT NULL, "s_categories" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "cards" table
CREATE TABLE "cards" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "position" double precision NOT NULL, "available" boolean NOT NULL DEFAULT true, "level" bigint NOT NULL DEFAULT 1, "experience_points" bigint NOT NULL DEFAULT 0, "experience_points_threshold" bigint NOT NULL DEFAULT 0, "rarity" bigint NOT NULL, "buffs" bigint NOT NULL DEFAULT 0, "individual_value" double precision NOT NULL, "metadata" jsonb NOT NULL, "owned_at" timestamptz NOT NULL, "card_type" character varying NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "cookies" table
CREATE TABLE "cookies" ("id" character varying NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "expires_at" timestamptz NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "dailies" table
CREATE TABLE "dailies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "has_voted" boolean NOT NULL DEFAULT false, "last_vote_at" timestamptz NOT NULL, "streak" bigint NOT NULL DEFAULT 0, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "dailies_player_id_key" to table: "dailies"
CREATE UNIQUE INDEX "dailies_player_id_key" ON "dailies" ("player_id");
-- Create "dungeons" table
CREATE TABLE "dungeons" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "seed" bigint NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "github_stars" table
CREATE TABLE "github_stars" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "github_user_id" character varying NULL, "has_starred" boolean NOT NULL DEFAULT false, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "github_stars_player_id_key" to table: "github_stars"
CREATE UNIQUE INDEX "github_stars_player_id_key" ON "github_stars" ("player_id");
-- Create "jobs" table
CREATE TABLE "jobs" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "jobkey" character varying NOT NULL, "retries" bigint NOT NULL DEFAULT 0, "run_at" timestamptz NOT NULL, "params" jsonb NOT NULL, "last_run_id" bigint NOT NULL DEFAULT 0, "recurring" boolean NOT NULL DEFAULT false, "delta_time" bigint NOT NULL DEFAULT 0, "errored" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- Create "listings" table
CREATE TABLE "listings" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "price" bigint NOT NULL, "note" character varying NULL, "card_id" uuid NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "loot_boxes" table
CREATE TABLE "loot_boxes" ("id" uuid NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "type" character varying NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "player_decks" table
CREATE TABLE "player_decks" ("create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "position" double precision NOT NULL, "player_id" character varying NOT NULL, "card_id" uuid NOT NULL, PRIMARY KEY ("player_id", "card_id"));
-- Create index "playerdeck_card_id" to table: "player_decks"
CREATE UNIQUE INDEX "playerdeck_card_id" ON "player_decks" ("card_id");
-- Create "player_favorite_cards" table
CREATE TABLE "player_favorite_cards" ("create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "position" double precision NOT NULL, "player_id" character varying NOT NULL, "card_id" uuid NOT NULL, PRIMARY KEY ("player_id", "card_id"));
-- Create index "playerfavoritecards_card_id" to table: "player_favorite_cards"
CREATE UNIQUE INDEX "playerfavoritecards_card_id" ON "player_favorite_cards" ("card_id");
-- Create "player_limits" table
CREATE TABLE "player_limits" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "dungeons_left" bigint NOT NULL DEFAULT 3, "dungeons_reset_at" timestamptz NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "player_limits_player_id_key" to table: "player_limits"
CREATE UNIQUE INDEX "player_limits_player_id_key" ON "player_limits" ("player_id");
-- Create "players" table
CREATE TABLE "players" ("id" character varying NOT NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "username" character varying NOT NULL DEFAULT '', "liens" bigint NOT NULL DEFAULT 500, "liens_in_auction" bigint NOT NULL DEFAULT 0, "level" bigint NOT NULL DEFAULT 1, "experience_points" bigint NOT NULL DEFAULT 0, "experience_points_threshold" bigint NOT NULL DEFAULT 0, "backpack_level" bigint NOT NULL DEFAULT 1, "backpack_reserved_slots" bigint NOT NULL DEFAULT 0, "selected_card_id" uuid NULL, PRIMARY KEY ("id"));
-- Modify "auction_bids" table
ALTER TABLE "auction_bids" ADD CONSTRAINT "auction_bids_auctions_bids" FOREIGN KEY ("auction_id") REFERENCES "auctions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "auction_bids_players_player" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "auctions" table
ALTER TABLE "auctions" ADD CONSTRAINT "auctions_cards_card" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "auctions_players_auctions" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "auth_states" table
ALTER TABLE "auth_states" ADD CONSTRAINT "auth_states_players_player" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "card_stats" table
ALTER TABLE "card_stats" ADD CONSTRAINT "card_stats_cards_stats" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "cards" table
ALTER TABLE "cards" ADD CONSTRAINT "cards_card_types_type" FOREIGN KEY ("card_type") REFERENCES "card_types" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "cards_players_cards" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "cookies" table
ALTER TABLE "cookies" ADD CONSTRAINT "cookies_players_player" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "dailies" table
ALTER TABLE "dailies" ADD CONSTRAINT "dailies_players_daily" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "dungeons" table
ALTER TABLE "dungeons" ADD CONSTRAINT "dungeons_players_dungeons" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "github_stars" table
ALTER TABLE "github_stars" ADD CONSTRAINT "github_stars_players_github_star" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "listings" table
ALTER TABLE "listings" ADD CONSTRAINT "listings_cards_card" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "listings_players_listings" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "loot_boxes" table
ALTER TABLE "loot_boxes" ADD CONSTRAINT "loot_boxes_players_lootboxes" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "player_decks" table
ALTER TABLE "player_decks" ADD CONSTRAINT "player_decks_cards_card" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "player_decks_players_player" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "player_favorite_cards" table
ALTER TABLE "player_favorite_cards" ADD CONSTRAINT "player_favorite_cards_cards_card" FOREIGN KEY ("card_id") REFERENCES "cards" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "player_favorite_cards_players_player" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "player_limits" table
ALTER TABLE "player_limits" ADD CONSTRAINT "player_limits_players_limits" FOREIGN KEY ("player_id") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "players" table
ALTER TABLE "players" ADD CONSTRAINT "players_cards_selected_card" FOREIGN KEY ("selected_card_id") REFERENCES "cards" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
