// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthGithubStates string
	Cards            string
	GithubStars      string
	Players          string
}{
	AuthGithubStates: "auth_github_states",
	Cards:            "cards",
	GithubStars:      "github_stars",
	Players:          "players",
}
