// Code generated by ent, DO NOT EDIT.

package playerlimit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the playerlimit type in the database.
	Label = "player_limit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldPlayerID holds the string denoting the player_id field in the database.
	FieldPlayerID = "player_id"
	// FieldDungeonsLeft holds the string denoting the dungeons_left field in the database.
	FieldDungeonsLeft = "dungeons_left"
	// FieldDungeonsResetAt holds the string denoting the dungeons_reset_at field in the database.
	FieldDungeonsResetAt = "dungeons_reset_at"
	// EdgeOf holds the string denoting the of edge name in mutations.
	EdgeOf = "of"
	// Table holds the table name of the playerlimit in the database.
	Table = "player_limits"
	// OfTable is the table that holds the of relation/edge.
	OfTable = "player_limits"
	// OfInverseTable is the table name for the Player entity.
	// It exists in this package in order to avoid circular dependency with the "player" package.
	OfInverseTable = "players"
	// OfColumn is the table column denoting the of relation/edge.
	OfColumn = "player_id"
)

// Columns holds all SQL columns for playerlimit fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldPlayerID,
	FieldDungeonsLeft,
	FieldDungeonsResetAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultDungeonsLeft holds the default value on creation for the "dungeons_left" field.
	DefaultDungeonsLeft int
	// DungeonsLeftValidator is a validator for the "dungeons_left" field. It is called by the builders before save.
	DungeonsLeftValidator func(int) error
)

// OrderOption defines the ordering options for the PlayerLimit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByPlayerID orders the results by the player_id field.
func ByPlayerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerID, opts...).ToFunc()
}

// ByDungeonsLeft orders the results by the dungeons_left field.
func ByDungeonsLeft(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDungeonsLeft, opts...).ToFunc()
}

// ByDungeonsResetAt orders the results by the dungeons_reset_at field.
func ByDungeonsResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDungeonsResetAt, opts...).ToFunc()
}

// ByOfField orders the results by of field.
func ByOfField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOfStep(), sql.OrderByField(field, opts...))
	}
}
func newOfStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OfInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OfTable, OfColumn),
	)
}
